old_sound_rabbit_mq:
    connections:
        default:
            host:             '%rabbitmq_host%'
            port:             '%rabbitmq_port%'
            user:             '%rabbitmq_user%'
            password:         '%rabbitmq_password%'
            vhost:            '%rabbitmq_vhost%'
    producers:
        weaving_the_web_amqp.twitter:
            connection:       default
            exchange_options: { name: 'twitter', type: topic }
        weaving_the_web_amqp.twitter.user_status:
            connection:       default
            exchange_options: { name: 'get-user-status', type: direct }
        weaving_the_web_amqp.twitter.news_status:
            connection:       default
            exchange_options: { name: 'get-news-status', type: direct }
        weaving_the_web_amqp.twitter.aggregates_status:
            connection:       default
            exchange_options: { name: 'get-aggregates-status', type: direct }
        weaving_the_web_amqp.producer.aggregates_likes:
            connection:       default
            exchange_options: { name: 'get-aggregates-likes', type: direct }
        weaving_the_web_amqp.producer.search_matching_statuses:
            connection:       default
            exchange_options: { name: 'get-search-matching-statuses', type: direct }
        weaving_the_web_amqp.producer.conversation_status:
            connection:       default
            exchange_options: { name: 'get-conversation-status', type: direct }
        weaving_the_web_amqp.producer.member_status:
            connection:       default
            exchange_options: { name: 'get-member-status', type: direct }
        weaving_the_web_amqp.producer.network:
            connection:       default
            exchange_options: { name: 'get-network', type: direct }
        weaving_the_web_amqp.producer.timely_status:
            connection:       default
            exchange_options: { name: 'get-timely-status', type: direct }
    anon_consumers:
        weaving_the_web_amqp.twitter:
            connection:       default
            exchange_options: { name: 'twitter', type: topic }
            callback:         weaving_the_web_amqp.twitter
    consumers:
        weaving_the_web_amqp.consumer.aggregates_likes:
            callback:         weaving_the_web_amqp.consumer.status
            connection:       default
            exchange_options: { name: 'get-aggregates-likes', type: direct }
            queue_options:    { name: 'get-aggregates-likes' }
            qos_options:      { prefetch_size: 0, prefetch_count: 1, global: false }
        weaving_the_web_amqp.consumer.conversation_status:
            callback:         weaving_the_web_amqp.consumer.conversation_status
            connection:       default
            exchange_options: { name: 'get-conversation-status', type: direct }
            queue_options:    { name: 'get-conversation-status' }
            qos_options:      { prefetch_size: 0, prefetch_count: 1, global: false }
        weaving_the_web_amqp.consumer.member_status:
            callback:         weaving_the_web_amqp.consumer.status
            connection:       default
            exchange_options: { name: 'get-member-status', type: direct }
            queue_options:    { name: 'get-member-status' }
            qos_options:      { prefetch_size: 0, prefetch_count: 1, global: false }
        weaving_the_web_amqp.consumer.timely_status:
            callback:         weaving_the_web_amqp.consumer.timely_status
            connection:       default
            exchange_options: { name: 'get-timely-status', type: direct }
            queue_options:    { name: 'get-timely-status' }
            qos_options:      { prefetch_size: 0, prefetch_count: 1, global: false }
        weaving_the_web_amqp.consumer.network:
            callback:         weaving_the_web_amqp.consumer.network
            connection:       default
            exchange_options: { name: 'get-network', type: direct }
            queue_options:    { name: 'get-network' }
            qos_options:      { prefetch_size: 0, prefetch_count: 1, global: false }
        weaving_the_web_amqp.twitter.user_status:
            callback:         weaving_the_web_amqp.consumer.status
            connection:       default
            exchange_options: { name: 'get-user-status', type: direct }
            queue_options:    { name: 'get-user-status' }
            qos_options:      { prefetch_size: 0, prefetch_count: 1, global: false }
        weaving_the_web_amqp.twitter.news_status:
            callback:         weaving_the_web_amqp.consumer.status
            connection:       default
            exchange_options: { name: 'get-news-status', type: direct }
            queue_options:    { name: 'get-news-status' }
            qos_options:      { prefetch_size: 0, prefetch_count: 1, global: false }
        weaving_the_web_amqp.twitter.aggregates_status:
            callback:         weaving_the_web_amqp.consumer.status
            connection:       default
            exchange_options: { name: 'get-aggregates-status', type: direct }
            queue_options:    { name: 'get-aggregates-status' }
            qos_options:      { prefetch_size: 0, prefetch_count: 1, global: false }
