parameters:
  monolog_channels:
    - 'deprecation' # Deprecations are logged in the dedicated "deprecation" channel when it exists
    - 'twitter_api'
    - 'development'
    - 'membership'

  main_log_level: debug

  monolog_stream_logging_handler:
    type:     stream
    path:     "%kernel.logs_dir%/%kernel.environment%.log"
    level:    "%main_log_level%"

  monolog_json_logging_handler:
    type:     stream
    path:     "%kernel.logs_dir%/%kernel.environment%.json"
    level:    info
    formatter: monolog.formatter.json

  monolog_stream_debug_logging_handler:
    type:       stream
    path:       "%kernel.logs_dir%/%kernel.environment%.log"
    level:      debug
    channels:   ["!event"]

  api.twitter.bearer_token:           '%env(resolve:API_TWITTER_BEARER_TOKEN)%'

  app.twitter_api.consumer_key:       '%env(resolve:API_TWITTER_CONSUMER_KEY)%'
  app.twitter_api.consumer_secret:    '%env(resolve:API_TWITTER_CONSUMER_SECRET)%'
  app.twitter.oauth_token.default:    '%env(resolve:API_TWITTER_USER_TOKEN)%'
  app.twitter.oauth_secret.default:   '%env(resolve:API_TWITTER_USER_SECRET)%'
  app.twitter.version:                '%env(resolve:API_TWITTER_VERSION)%'

  publishers_list_default:            '%env(resolve:PUBLISHERS_LIST_DEFAULT)%'

  repository.publishers_list.class:   'App\Twitter\Infrastructure\Http\Repository\PublishersListRepository'
