services:
    App\Api\AccessToken\TokenChange:
        class: 'App\Api\AccessToken\TokenChange'
        arguments:
            - '@weaving_the_web_twitter.repository.token'
            - '@logger'

    App\Infrastructure\Twitter\Api\Accessor\OwnershipAccessor:
        class: 'App\Infrastructure\Twitter\Api\Accessor\OwnershipAccessor'
        arguments:
            - '@weaving_the_web_twitter.api_accessor'
            - '@weaving_the_web_twitter.repository.token'
            - '@App\Api\AccessToken\TokenChange'
            - '@logger'
        calls:
            - [ 'setOwnershipBatchCollectedEventRepository', [ '@App\Infrastructure\Collection\Repository\OwnershipBatchCollectedEventRepository'] ]

    App\Infrastructure\Twitter\Api\Accessor\MemberProfileAccessor:
        class: 'App\Infrastructure\Twitter\Api\Accessor\MemberProfileAccessor'
        arguments:
            - '@weaving_the_web_twitter.api_accessor'
            - '@user_manager'
            - '@App\Infrastructure\Twitter\Api\UnavailableResourceHandler'
