parameters:
    command.map_status_collection.class:                                        'App\Twitter\Infrastructure\Publication\Mapping\Command\MapStatusCollectionCommand'
    command.select_status_collection.class:                                     'App\Twitter\Infrastructure\Publication\Command\QueryPublicationCollectionCommand'
    command.import_network.class:                                               'App\Membership\Infrastructure\Console\ImportNetworkCommand'

    weaving_the_web_amqp.consumer.conversation_status.class:                    'App\Conversation\Consumer\ConversationStatusConsumer'
    weaving_the_web_amqp.producer.produce_conversation_messages_command.class:  'App\Conversation\Producer\ProduceConversationMessagesCommand'
    weaving_the_web_amqp.producer.produce_member_messages_command.class:        'App\Conversation\Producer\ProduceMemberMessagesCommand'
    weaving_the_web_amqp.consumer.network.class:                                'App\Membership\Infrastructure\Consumer\NetworkConsumer'

services:
    App\Twitter\Infrastructure\Subscription\Console\UnfollowDiffSubscriptionsSubscribeesCommand:
        class: 'App\Twitter\Infrastructure\Subscription\Console\UnfollowDiffSubscriptionsSubscribeesCommand'
        tags:
            - { name: 'console.command' }
        calls:
            - [ 'setLogger', ['@logger'] ]
            - [ 'setMemberRepository', ['@App\Membership\Infrastructure\Repository\MemberRepository'] ]
            - [ 'setMemberSubscriptionRepository', ['@repository.member_subscription'] ]
            - [ 'setMutator', ['@App\Twitter\Infrastructure\Api\Mutator\FriendshipMutator'] ]
            - [ 'setNetworkRepository', ['@App\Membership\Infrastructure\Repository\NetworkRepository'] ]
            - [ 'setSubscribeesRepository', ['@App\Twitter\Infrastructure\Curation\Repository\FollowersListCollectedEventRepository'] ]
            - [ 'setSubscriptionsRepository', ['@App\Twitter\Infrastructure\Curation\Repository\FriendsListCollectedEventRepository'] ]

    App\Twitter\Infrastructure\Amqp\Command\DispatchFetchTweetsMessages:
        class: 'App\Twitter\Infrastructure\Amqp\Command\DispatchFetchTweetsMessages'
        calls:
            - [ 'setAccessor',                      [ '@App\Twitter\Domain\Api\Accessor\ApiAccessorInterface'] ]
            - [ 'setAggregateRepository',           [ '@App\Twitter\Infrastructure\Api\Repository\PublishersListRepository'] ]
            - [ 'setDefaultSecret',                 [ '%app.twitter.oauth_secret.default%'] ]
            - [ 'setDefaultToken',                  [ '%app.twitter.oauth_token.default%'] ]
            - [ 'setTokenRepository',               [ '@App\Twitter\Domain\Api\AccessToken\Repository\TokenRepositoryInterface'] ]
            - [ 'setFetchTweetsMessageDispatcher',  [ '@App\Twitter\Infrastructure\Amqp\MessageBus\FetchTweetsMessageDispatcher'] ]
            - [ 'setTranslator',                    [ '@App\Twitter\Infrastructure\Translation\Translator'] ]
            - [ 'setEntityManager',                 [ '@doctrine.orm.entity_manager'] ]
            - [ 'setLogger',                        [ '@logger'] ]
        tags:
            - { name: 'console.command' }
        public: true

    App\Twitter\Infrastructure\Amqp\Command\FetchMemberSubscriptionTimelineMessageDispatcher:
        class: 'App\Twitter\Infrastructure\Amqp\Command\FetchMemberSubscriptionTimelineMessageDispatcher'
        calls:
            - [ 'setAccessor',                              [ '@App\Twitter\Domain\Api\Accessor\ApiAccessorInterface'] ]
            - [ 'setAggregateRepository',                   [ '@App\Twitter\Infrastructure\Api\Repository\PublishersListRepository'] ]
            - [ 'setDefaultSecret',                         [ '%app.twitter.oauth_secret.default%'] ]
            - [ 'setDefaultToken',                          [ '%app.twitter.oauth_token.default%'] ]
            - [ 'setEntityManager',                         [ '@doctrine.orm.entity_manager'] ]
            - [ 'setLogger',                                [ '@logger'] ]
            - [ 'setMemberFriendsCollectedEventRepository', [ '@App\Twitter\Infrastructure\Curation\Repository\MemberFriendsCollectedEventRepository'] ]
            - [ 'setMemberProfileCollectedEventRepository', [ '@App\Twitter\Infrastructure\Curation\Repository\MemberProfileCollectedEventRepository'] ]
            - [ 'setMemberRepository',                      [ '@App\Membership\Infrastructure\Repository\MemberRepository'] ]
            - [ 'setMessageBus',                            [ '@messenger.default_bus'] ]
            - [ 'setTranslator',                            [ '@translator'] ]
        tags:
            - { name: 'console.command' }
        public: true

    App\Twitter\Infrastructure\Console\MigrateStatusToPublicationsCommand:
        class: 'App\Twitter\Infrastructure\Console\MigrateStatusToPublicationsCommand'
        calls:
            - [ 'setPublicationRepository', [ '@App\Twitter\Infrastructure\Publication\Repository\PublicationRepository' ] ]
        tags:
            - { name: 'console.command' }

    command.import_media_relationships:
        class: 'App\FrenchMediaShareholders\Console\ImportFrenchMediaShareholdersCommand'
        properties:
            logger:          '@logger'
            mediaRepository: '@repository.media'
            mediasDirectory: '%kernel.project_dir%/../var/home/medias'
            ownerRepository: '@repository.owner'
        tags:
            - { name: 'console.command' }

    command.select_status_collection:
        class: "%command.select_status_collection.class%"
        properties:
            statusRepository: '@App\Twitter\Infrastructure\Api\Repository\StatusRepository'
        tags:
            - { name: 'console.command' }

    command.import_network:
        class: "%command.import_network.class%"
        properties:
            networkRepository: '@App\Membership\Infrastructure\Repository\NetworkRepository'
            #
            #
            # TODO
            # Replace rabbimq bundle messager producer with
            # symfony component message dispatcher
            #
            # producer:          '@old_sound_rabbit_mq.weaving_the_web_amqp.producer.network_producer'
        tags:
            - { name: 'console.command' }

    command.map_status_collection:
        class: "%command.map_status_collection.class%"
        properties:
            statusRepository:       '@App\Twitter\Infrastructure\Api\Repository\StatusRepository'
            refreshStatusMapping:   '@mapping.refresh_status'
            oauthToken:             "%app.twitter.oauth_token.default%"
            oauthSecret:            "%app.twitter.oauth_secret.default%"
        tags:
            - { name: 'console.command' }

    command.recommend_subscriptions:
        class: 'App\Recommendation\Infrastructure\Console\RecommendSubscriptionsCommand'
        properties:
            entityManager:      '@doctrine.orm.entity_manager'
        tags:
            - { name: 'console.command' }

    command.subscribe_to_member_timelines:
        class: 'App\Membership\Infrastructure\Console\SubscribeToMemberTimelinesCommand'
        properties:
            accessor:                        '@App\Twitter\Domain\Api\Accessor\ApiAccessorInterface'
            aggregateSubscriptionRepository: '@App\Membership\Infrastructure\Repository\AggregateSubscriptionRepository'
            logger:                          '@logger'
        tags:
            - { name: 'console.command' }

    weaving_the_web_amqp.consumer.conversation_status:
        class: "%weaving_the_web_amqp.consumer.conversation_status.class%"
        calls:
            - [ 'setLogger',            [ '@monolog.logger.twitter_api'] ]
            - [ 'setStatusAccessor',    [ '@App\Twitter\Infrastructure\Api\Accessor\StatusAccessor' ] ]
            - [ 'setStatusRepository',  [ '@App\Twitter\Infrastructure\Api\Repository\StatusRepository' ] ]
            - [ 'setUserRepository',    [ '@user_manager'] ]
        properties:
            aggregateRepository:    '@App\Twitter\Infrastructure\Api\Repository\PublishersListRepository'
            entityManager:          '@doctrine.orm.entity_manager'

    weaving_the_web_amqp.producer.conversation_status:
        class: "%weaving_the_web_amqp.producer.produce_conversation_messages_command.class%"
        properties:
            filesystem:      '@filesystem'
            statusDirectory: "%kernel.project_dir%/../src/App/Resources/statuses"
        tags:
            - { name: 'console.command' }

    weaving_the_web_amqp.producer.member_status:
        class: "%weaving_the_web_amqp.producer.produce_member_messages_command.class%"
        properties:
            statusDirectory: "%kernel.project_dir%/../src/App/Resources/statuses"
        tags:
            - { name: 'console.command' }
