parameters:
    command.map_status_collection.class:                                        'App\Twitter\Infrastructure\Publication\Mapping\Command\MapStatusCollectionCommand'
    command.select_status_collection.class:                                     'App\Twitter\Infrastructure\Publication\Command\QueryPublicationCollectionCommand'

    app.amqp_message_consumer.conversation_status.class:                        'App\Conversation\Consumer\ConversationStatusConsumer'

services:
    App\Membership\Infrastructure\Console\AddSingleMemberToListCommand:
        class: 'App\Membership\Infrastructure\Console\AddSingleMemberToListCommand'
        properties:
            editListMembers: '@App\Membership\Domain\Repository\EditListMembersInterface'
            logger:                     '@logger'
        tags:
            - { name: 'console.command' }

    App\QualityAssurance\Infrastructure\Console\GuardAgainstMissingMediaCommand:
        class: 'App\QualityAssurance\Infrastructure\Console\GuardAgainstMissingMediaCommand'
        calls:
            - [ 'setHttpClient',                   ['@App\QualityAssurance\Infrastructure\HttpClient\HttpClient'] ]
            - [ 'setEntityManager',                ['@doctrine.orm.entity_manager'] ]
            - [ 'setLogger',                       ['@logger'] ]
            - [ 'setMemberProfileAwareHttpClient', ['@App\Twitter\Domain\Http\Client\MemberProfileAwareHttpClientInterface'] ]
            - [ 'setNotFoundTweetRepository',      ['@App\Twitter\Domain\Publication\Repository\NotFoundTweetRepositoryInterface'] ]
            - [ 'setResourcesDir',                 ['%kernel.project_dir%/src/QualityAssurance/Infrastructure/Resources'] ]
            - [ 'setTrendsRepository',             ['@App\QualityAssurance\Domain\Repository\TrendsRepositoryInterface'] ]
            - [ 'setTweetCurator',                 ['@App\Twitter\Domain\Curation\Curator\TweetCuratorInterface'] ]
            - [ 'setTweetRepository',              ['@App\Twitter\Domain\Publication\Repository\TweetRepositoryInterface'] ]
        tags:
            - { name: 'console.command' }

    App\QualityAssurance\Infrastructure\Console\GuardAgainstMissingMemberProfilePictureCommand:
        class: 'App\QualityAssurance\Infrastructure\Console\GuardAgainstMissingMemberProfilePictureCommand'
        calls:
            - [ 'setHttpClient',                   ['@App\QualityAssurance\Infrastructure\HttpClient\HttpClient'] ]
            - [ 'setEntityManager',                ['@doctrine.orm.entity_manager'] ]
            - [ 'setLogger',                       ['@logger'] ]
            - [ 'setMemberProfileAwareHttpClient', ['@App\Twitter\Domain\Http\Client\MemberProfileAwareHttpClientInterface'] ]
            - [ 'setNotFoundTweetRepository',      ['@App\Twitter\Domain\Publication\Repository\NotFoundTweetRepositoryInterface'] ]
            - [ 'setResourcesDir',                 ['%kernel.project_dir%/src/QualityAssurance/Infrastructure/Resources'] ]
            - [ 'setTweetRepository',              ['@App\Twitter\Domain\Publication\Repository\TweetRepositoryInterface'] ]
        tags:
            - { name: 'console.command' }

    App\QualityAssurance\Infrastructure\HttpClient\HttpClient:
        class: 'App\QualityAssurance\Infrastructure\HttpClient\HttpClient'

    App\Twitter\Infrastructure\Subscription\Console\UnfollowDiffSubscriptionsSubscribeesCommand:
        class: 'App\Twitter\Infrastructure\Subscription\Console\UnfollowDiffSubscriptionsSubscribeesCommand'
        tags:
            - { name: 'console.command' }
        calls:
            - [ 'setLogger',                        ['@logger'] ]
            - [ 'setMemberRepository',              ['@App\Membership\Infrastructure\Repository\MemberRepository'] ]
            - [ 'setMemberSubscriptionRepository',  ['@repository.member_subscription'] ]
            - [ 'setMutator',                       ['@App\Twitter\Infrastructure\Http\Mutator\FriendshipMutator'] ]
            - [ 'setNetworkRepository',             ['@App\Membership\Infrastructure\Repository\NetworkRepository'] ]
            - [ 'setSubscribeesRepository',         ['@App\Twitter\Infrastructure\Curation\Repository\FollowersListCollectedEventRepository'] ]
            - [ 'setSubscriptionsRepository',       ['@App\Twitter\Infrastructure\Curation\Repository\FriendsListCollectedEventRepository'] ]

    App\Twitter\Infrastructure\Amqp\MessageBus\FetchTweetsAmqpMessagesDispatcherCommand:
        class: 'App\Twitter\Infrastructure\Amqp\MessageBus\FetchTweetsAmqpMessagesDispatcherCommand'
        calls:
            - [ 'setAggregateRepository',               [ '@App\Twitter\Infrastructure\Http\Repository\PublishersListRepository'] ]
            - [ 'setDefaultSecret',                     [ '%app.twitter.oauth_secret.default%'] ]
            - [ 'setDefaultToken',                      [ '%app.twitter.oauth_token.default%'] ]
            - [ 'setHttpClient',                        [ '@App\Twitter\Domain\Http\Client\HttpClientInterface'] ]
            - [ 'setTokenRepository',                   [ '@App\Twitter\Domain\Http\AccessToken\Repository\TokenRepositoryInterface'] ]
            - [ 'setFetchTweetsAmqpMessagesDispatcher', [ '@App\Twitter\Infrastructure\Amqp\MessageBus\FetchTweetsAmqpMessagesDispatcher'] ]
            - [ 'setTranslator',                        [ '@App\Twitter\Infrastructure\Translation\Translator'] ]
            - [ 'setEntityManager',                     [ '@doctrine.orm.entity_manager'] ]
            - [ 'setLogger',                            [ '@logger'] ]
        tags:
            - { name: 'console.command' }
        public: true

    App\Twitter\Infrastructure\Console\MigrateStatusToPublicationsCommand:
        class: 'App\Twitter\Infrastructure\Console\MigrateStatusToPublicationsCommand'
        calls:
            - [ 'setTweetPublicationPersistenceLayer', [ '@App\Twitter\Infrastructure\Publication\Repository\TweetPublicationPersistenceLayer' ] ]
        tags:
            - { name: 'console.command' }

    App\Twitter\Infrastructure\Http\Client\Fallback\TwitterHttpApiClient:
        class: 'App\Twitter\Infrastructure\Http\Client\Fallback\TwitterHttpApiClient'
        arguments:
            - '%api.twitter.bearer_token%'
            - '@Symfony\Contracts\HttpClient\HttpClientInterface'
            - '@App\Twitter\Domain\Persistence\TweetPersistenceLayerInterface'
            - '@logger'

    App\Twitter\Domain\Http\Client\Fallback\TwitterHttpApiClientInterface:
        '@App\Twitter\Infrastructure\Http\Client\Fallback\TwitterHttpApiClient'

    App\Twitter\Infrastructure\Security\Console\RequestTwitterApiAccessTokenCommand:
        class: 'App\Twitter\Infrastructure\Security\Console\RequestTwitterApiAccessTokenCommand'
        arguments:
            - '@App\Twitter\Domain\Http\Client\HttpClientInterface'
        tags:
            - { name: 'console.command' }

    command.import_media_relationships:
        class: 'App\FrenchMediaShareholders\Console\ImportFrenchMediaShareholdersCommand'
        properties:
            logger:          '@logger'
            mediaRepository: '@repository.media'
            mediasDirectory: '%kernel.project_dir%/../var/home/medias'
            ownerRepository: '@repository.owner'
        tags:
            - { name: 'console.command' }

    command.select_status_collection:
        class: "%command.select_status_collection.class%"
        properties:
            tweetRepository: '@App\Twitter\Domain\Publication\Repository\TweetRepositoryInterface'
        tags:
            - { name: 'console.command' }

    command.map_status_collection:
        class: "%command.map_status_collection.class%"
        properties:
            tweetRepository: '@App\Twitter\Domain\Publication\Repository\TweetRepositoryInterface'
            refreshStatusMapping:   '@mapping.refresh_status'
            oauthToken:             "%app.twitter.oauth_token.default%"
            oauthSecret:            "%app.twitter.oauth_secret.default%"
        tags:
            - { name: 'console.command' }

    command.recommend_subscriptions:
        class: 'App\Recommendation\Infrastructure\Console\RecommendSubscriptionsCommand'
        properties:
            entityManager:          '@doctrine.orm.entity_manager'
        tags:
            - { name: 'console.command' }

    app.amqp_message_consumer.conversation_status:
        class: "%app.amqp_message_consumer.conversation_status.class%"
        calls:
            - [ 'setLogger',                [ '@monolog.logger.twitter_api'] ]
            - [ 'setTweetAwareHttpClient',  [ '@App\Twitter\Infrastructure\Http\Client\TweetAwareHttpClient' ] ]
            - [ 'setTweetRepository',      [ '@App\Twitter\Domain\Publication\Repository\TweetRepositoryInterface' ] ]
            - [ 'setMemberRepository',      [ '@user_manager'] ]
        properties:
            aggregateRepository:        '@App\Twitter\Infrastructure\Http\Repository\PublishersListRepository'
            entityManager:              '@doctrine.orm.entity_manager'

