services:
    controller.healthcheck:
        public: true
        class: 'App\Twitter\Infrastructure\Healthcheck\Controller\HealthcheckController'
        arguments:
            - '%allowed.origin%'
            - '%kernel.environment%'

    controller.list:
        public: true
        class: 'App\PublishersList\Controller\ListController'
        arguments:
            - '%allowed.origin%'
            - '%kernel.environment%'
        calls:
            - [ 'setPublishersListDispatcher', ['@App\Twitter\Infrastructure\Amqp\MessageBus\PublishersListDispatcher']]
        properties:
            logger:                         '@logger'
            highlightRepository:            '@repository.highlight'
            memberRepository:               '@user_manager'
            redisCache:                     '@app.cache.redis'
            router:                         '@router'
            popularPublicationRepository:   '@App\NewsReview\Infrastructure\Repository\PopularPublicationRepository'
            tokenRepository:                '@repository.access_token'

    App\PublishersList\Controller\ListController: '@controller.list'
    controller.publication:
        public: true
        class: 'App\Twitter\Infrastructure\Publication\Controller\PublicationController'
        arguments:
            - '%allowed.origin%'
            - '%kernel.environment%'
        calls:
            - [ 'setCache',                 [ '@app.cache.redis' ]]
            - [ 'setLogger',            [ '@logger' ] ]
            - [ 'setPublicationRepository', [ '@App\Twitter\Infrastructure\Publication\Repository\PublicationRepository' ]]
            - [ 'setStatusAccessor',    [ '@App\Twitter\Infrastructure\Twitter\Api\Accessor\StatusAccessor' ]]
            - [ 'setStatusRepository',  [ '@App\Twitter\Infrastructure\Api\Repository\StatusRepository' ]]

