services:
    App\Twitter\Infrastructure\Healthcheck\Controller\HealthcheckController:
        public: true
        class: 'App\Twitter\Infrastructure\Healthcheck\Controller\HealthcheckController'
        arguments:
            - '%allowed.origin%'
            - '%kernel.environment%'

    App\Trends\Infrastructure\Controller\ListController:
        public: true
        class: 'App\Trends\Infrastructure\Controller\ListController'
        arguments:
            - '%allowed.origin%'
            - '%kernel.environment%'
        properties:
            logger:                         '@logger'
            highlightRepository:            '@repository.highlight'
            memberRepository:               '@user_manager'
            redisCache:                     '@app.cache.redis'
            router:                         '@router'
            popularPublicationRepository:   '@App\Trends\Infrastructure\Repository\PopularPublicationRepository'
            tokenRepository:                '@repository.access_token'
