services:
    controller.authentication:
        public: true
        class: 'App\Member\Authentication\Controller\AuthenticationController'
        properties:
            authenticator:        '@app.authenticator'

    controller.list:
        public: true
        class: 'App\Aggregate\Controller\ListController'
        properties:
            allowedOrigin:                  '%allowed.origin%'
            configDirectory:                '%kernel.project_dir%/config'
            authenticationTokenRepository:  '@repository.authentication_token'
#            aggregateLikesProducer:         '@old_sound_rabbit_mq.weaving_the_web_amqp.producer.aggregates_likes_producer'
            aggregateRepository:            '@repository.publication_list'
#            aggregateStatusesProducer:      '@old_sound_rabbit_mq.weaving_the_web_amqp.twitter.aggregates_status_producer'
            environment:                    '%kernel.environment%'
            highlightRepository:            '@repository.highlight'
            logger:                         '@logger'
            memberRepository:               '@user_manager'
            router:                         '@router'
            redisCache:                     '@app.cache.redis'
            timelyStatusRepository:         '@repository.timely_status'
            tokenRepository:                '@repository.access_token'

    controller.logged_in_member:
        public: true
        class: 'App\Member\Controller\LoggedInMemberController'
        properties:
            logger:                        '@logger'
            authenticationTokenRepository: '@repository.authentication_token'
            allowedOrigin:                 '%allowed.origin%'
            environment:                   '%kernel.environment%'

    controller.aggregate:
        public: true
        class: 'App\Aggregate\Controller\AggregateController'
        properties:
            aggregateRepository: '@repository.publication_list'
            allowedOrigin:       '%allowed.origin%'
            environment:         '%kernel.environment%'
            redisCache:          '@app.cache.redis'

    controller.keyword:
        public: true
        class: 'App\Aggregate\Controller\KeywordController'
        properties:
            keywordRepository: '@repository.keyword'
            allowedOrigin:     '%allowed.origin%'
            environment:       '%kernel.environment%'
            redisCache:        '@app.cache.redis'
