services:
    App\Infrastructure\Twitter\Collector\InterruptibleCollectDecider:
        class: 'App\Infrastructure\Twitter\Collector\InterruptibleCollectDecider'
        calls:
            - [ 'setApiAccessor',                           [ '@App\Twitter\Api\Accessor'] ]
            - [ 'setLogger',                                [ '@logger' ] ]
            - [ 'setLikedStatusRepository',                 [ '@repository.liked_status' ] ]
            - [ 'setLikedStatusCollectDecider',             [ '@App\Infrastructure\Twitter\Collector\LikedStatusCollectDecider' ] ]
            - [ 'setMemberProfileCollectedEventRepository', [ '@App\Infrastructure\Curation\Repository\MemberProfileCollectedEventRepository' ] ]
            - [ 'setMemberRepository',                      [ '@App\Infrastructure\Repository\Membership\MemberRepository' ] ]
            - [ 'setModerator',                             [ '@App\Infrastructure\Api\Moderator\ApiLimitModerator' ] ]
            - [ 'setPublishersListRepository',             [ '@App\Infrastructure\Api\Repository\PublishersListRepository' ] ]
            - [ 'setStatusAccessor',                        [ '@App\Infrastructure\Twitter\Api\Accessor\StatusAccessor' ] ]
            - [ 'setStatusRepository',                      [ '@App\Infrastructure\Api\Repository\StatusRepository' ] ]
            - [ 'setStatusPersistence',                     [ '@App\Infrastructure\Publication\Persistence\StatusPersistence' ] ]
            - [ 'setTokenRepository',                       [ '@repository.access_token' ] ]
            - [ 'setWhispererRepository',                   [ '@repository.whisperer' ] ]
        public: true

    App\Infrastructure\Twitter\Collector\LikedStatusCollectDecider:
        class: 'App\Infrastructure\Twitter\Collector\LikedStatusCollectDecider'
        calls:
            - [ 'setLikedStatusRepository',      [ '@repository.liked_status' ] ]
            - [ 'setStatusAccessor',             [ '@App\Infrastructure\Twitter\Api\Accessor\StatusAccessor' ] ]
            - [ 'setStatusRepository',           [ '@App\Infrastructure\Api\Repository\StatusRepository' ] ]
            - [ 'setStatusPersistence',          [ '@App\Infrastructure\Publication\Persistence\StatusPersistence' ] ]
