services:

    App\Twitter\Infrastructure\Curation\InterruptibleCurator:
        class: 'App\Twitter\Infrastructure\Curation\InterruptibleCurator'
        calls:
            - [ 'setHttpClient',                            [ '@App\Twitter\Domain\Http\Client\HttpClientInterface'] ]
            - [ 'setLogger',                                [ '@logger' ] ]
            - [ 'setMemberProfileCollectedEventRepository', [ '@App\Twitter\Infrastructure\Curation\Repository\MemberProfileCollectedEventRepository' ] ]
            - [ 'setMemberRepository',                      [ '@App\Membership\Infrastructure\Repository\MemberRepository' ] ]
            - [ 'setRateLimitCompliance',                   [ '@App\Twitter\Infrastructure\Http\Compliance\RateLimitCompliance' ] ]
            - [ 'setPublishersListRepository',              [ '@App\Twitter\Infrastructure\Http\Repository\PublishersListRepository' ] ]
            - [ 'setTweetAwareHttpClient',                  [ '@App\Twitter\Infrastructure\Http\Client\TweetAwareHttpClient' ] ]
            - [ 'setTweetRepository',                      [ '@App\Twitter\Infrastructure\Http\Repository\TweetRepository' ] ]
            - [ 'setTokenRepository',                       [ '@App\Twitter\Domain\Http\AccessToken\Repository\TokenRepositoryInterface' ] ]
            - [ 'setTweetPersistenceLayer',                 [ '@App\Twitter\Domain\Persistence\TweetPersistenceLayerInterface' ] ]
            - [ 'setWhispererRepository',                   [ '@repository.whisperer' ] ]
        public: true

    App\Twitter\Infrastructure\Amqp\MessageHandler\FetchTweetMessageHandler:
        class: 'App\Twitter\Infrastructure\Amqp\MessageHandler\FetchTweetMessageHandler'
        calls:
            - [ 'setCurator',           [ '@App\Twitter\Infrastructure\Curation\TweetCurator' ] ]
            - [ 'setLogger',            [ '@monolog.logger.twitter_api' ] ]
            - [ 'setMemberRepository',  [ '@App\Membership\Infrastructure\Repository\MemberRepository' ] ]
        properties:
            tokenRepository:            '@App\Twitter\Domain\Http\AccessToken\Repository\TokenRepositoryInterface'
        tags:
            -
                name:       'messenger.message_handler'
                handles:    'App\Twitter\Infrastructure\Amqp\Message\FetchAuthoredTweet'
