services:

    App\Twitter\Infrastructure\Collector\InterruptibleCurator:
        class: 'App\Twitter\Infrastructure\Collector\InterruptibleCurator'
        calls:
            - [ 'setHttpClient',                           [ '@App\Twitter\Domain\Http\Client\HttpClientInterface'] ]
            - [ 'setLogger',                                [ '@logger' ] ]
            - [ 'setMemberProfileCollectedEventRepository', [ '@App\Twitter\Infrastructure\Curation\Repository\MemberProfileCollectedEventRepository' ] ]
            - [ 'setMemberRepository',                      [ '@App\Membership\Infrastructure\Repository\MemberRepository' ] ]
            - [ 'setRateLimitCompliance',                             [ '@App\Twitter\Infrastructure\Http\Compliance\RateLimitCompliance' ] ]
            - [ 'setPublishersListRepository',             [ '@App\Twitter\Infrastructure\Http\Repository\PublishersListRepository' ] ]
            - [ 'setTweetAwareHttpClient',                        [ '@App\Twitter\Infrastructure\Http\Client\TweetAwareHttpClient' ] ]
            - [ 'setStatusRepository',                      [ '@App\Twitter\Infrastructure\Http\Repository\StatusRepository' ] ]
            - [ 'setStatusPersistence',                     [ '@App\Twitter\Infrastructure\Publication\Persistence\StatusPersistence' ] ]
            - [ 'setTokenRepository',                       [ '@App\Twitter\Domain\Http\AccessToken\Repository\TokenRepositoryInterface' ] ]
            - [ 'setWhispererRepository',                   [ '@repository.whisperer' ] ]
        public: true

    App\Twitter\Infrastructure\Amqp\MessageHandler\FetchTweetMessageHandler:
        class: 'App\Twitter\Infrastructure\Amqp\MessageHandler\FetchTweetMessageHandler'
        calls:
            - [ 'setCurator',           [ '@App\Twitter\Infrastructure\Collector\TweetCurator' ] ]
            - [ 'setLogger',            [ '@monolog.logger.twitter_api' ] ]
            - [ 'setMemberRepository',  [ '@App\Membership\Infrastructure\Repository\MemberRepository' ] ]
        properties:
            tokenRepository:            '@App\Twitter\Domain\Http\AccessToken\Repository\TokenRepositoryInterface'
        tags:
            -
                name:       'messenger.message_handler'
                handles:    'App\Twitter\Infrastructure\Amqp\Message\FetchTweet'