services:

    App\Twitter\Infrastructure\Collector\InterruptibleCurator:
        class: 'App\Twitter\Infrastructure\Collector\InterruptibleCurator'
        calls:
            - [ 'setApiAccessor',                           [ '@App\Twitter\Domain\Api\Accessor\ApiAccessorInterface'] ]
            - [ 'setLogger',                                [ '@logger' ] ]
            - [ 'setMemberProfileCollectedEventRepository', [ '@App\Twitter\Infrastructure\Curation\Repository\MemberProfileCollectedEventRepository' ] ]
            - [ 'setMemberRepository',                      [ '@App\Membership\Infrastructure\Repository\MemberRepository' ] ]
            - [ 'setModerator',                             [ '@App\Twitter\Infrastructure\Api\Moderator\ApiLimitModerator' ] ]
            - [ 'setPublishersListRepository',             [ '@App\Twitter\Infrastructure\Api\Repository\PublishersListRepository' ] ]
            - [ 'setStatusAccessor',                        [ '@App\Twitter\Infrastructure\Api\Accessor\StatusAccessor' ] ]
            - [ 'setStatusRepository',                      [ '@App\Twitter\Infrastructure\Api\Repository\StatusRepository' ] ]
            - [ 'setStatusPersistence',                     [ '@App\Twitter\Infrastructure\Publication\Persistence\StatusPersistence' ] ]
            - [ 'setTokenRepository',                       [ '@App\Twitter\Domain\Api\AccessToken\Repository\TokenRepositoryInterface' ] ]
            - [ 'setWhispererRepository',                   [ '@repository.whisperer' ] ]
        public: true

    App\Twitter\Infrastructure\Amqp\MessageHandler\FetchTweetMessageHandler:
        class: 'App\Twitter\Infrastructure\Amqp\MessageHandler\FetchTweetMessageHandler'
        calls:
            - [ 'setCurator',           [ '@App\Twitter\Infrastructure\Collector\TweetCurator' ] ]
            - [ 'setLogger',            [ '@monolog.logger.twitter_api' ] ]
            - [ 'setMemberRepository',  [ '@App\Membership\Infrastructure\Repository\MemberRepository' ] ]
        properties:
            tokenRepository:            '@App\Twitter\Domain\Api\AccessToken\Repository\TokenRepositoryInterface'
        tags:
            -
                name:       'messenger.message_handler'
                handles:    'App\Twitter\Infrastructure\Amqp\Message\FetchTweet'