services:

    App\Twitter\Infrastructure\Collector\InterruptibleCollectDecider:
        class: 'App\Twitter\Infrastructure\Collector\InterruptibleCollectDecider'
        calls:
            - [ 'setApiAccessor',                           [ '@App\Twitter\Domain\Api\Accessor\ApiAccessorInterface'] ]
            - [ 'setLogger',                                [ '@logger' ] ]
            - [ 'setMemberProfileCollectedEventRepository', [ '@App\Twitter\Infrastructure\Curation\Repository\MemberProfileCollectedEventRepository' ] ]
            - [ 'setMemberRepository',                      [ '@App\Twitter\Infrastructure\Membership\Repository\MemberRepository' ] ]
            - [ 'setModerator',                             [ '@App\Twitter\Infrastructure\Api\Moderator\ApiLimitModerator' ] ]
            - [ 'setPublishersListRepository',             [ '@App\Twitter\Infrastructure\Api\Repository\PublishersListRepository' ] ]
            - [ 'setStatusAccessor',                        [ '@App\Twitter\Infrastructure\Api\Accessor\StatusAccessor' ] ]
            - [ 'setStatusRepository',                      [ '@App\Twitter\Infrastructure\Api\Repository\StatusRepository' ] ]
            - [ 'setStatusPersistence',                     [ '@App\Twitter\Infrastructure\Publication\Persistence\StatusPersistence' ] ]
            - [ 'setTokenRepository',                       [ '@App\Twitter\Domain\Api\AccessToken\Repository\TokenRepositoryInterface' ] ]
            - [ 'setWhispererRepository',                   [ '@repository.whisperer' ] ]
        public: true

    App\NewsReview\Infrastructure\Repository\PublishersListRepository:
        class: 'App\NewsReview\Infrastructure\Repository\PublishersListRepository'
        arguments:
            - '@App\Twitter\Domain\Publication\Repository\PublishersListRepositoryInterface'

    App\NewsReview\Domain\Repository\PublishersListRepositoryInterface:
        '@App\NewsReview\Infrastructure\Repository\PublishersListRepository'
