services:
    mapping.identity:
        class: 'App\StatusCollection\Mapping\IdentityMapping'

    mapping.refresh_status:
        class: 'App\StatusCollection\Mapping\RefreshStatusMapping'
        arguments:
            - '@App\Twitter\Api\Accessor'
        calls:
            - [ 'setLogger', [ '@monolog.logger.status'  ] ]
            - [ 'setPublicationPersistence', [ '@App\Infrastructure\Status\Persistence\PublicationPersistence'  ] ]
            - [ 'setStatusRepository', [ '@App\Api\Repository\StatusRepository'  ] ]
