services:
    mapping.identity:
        class: 'App\Twitter\Infrastructure\Publication\Mapping\IdentityMapping'

    mapping.refresh_status:
        class: 'App\Twitter\Infrastructure\Publication\Mapping\RefreshStatusMapping'
        arguments:
            - '@App\Twitter\Domain\Http\Client\HttpClientInterface'
        calls:
            - [ 'setLogger',            [ '@App\Twitter\Infrastructure\Log\TweetCurationLogger'  ] ]
            - [ 'setPersistenceLayer',  [ '@App\Twitter\Domain\Persistence\PersistenceLayerInterface'  ] ]
            - [ 'setStatusRepository',  [ '@App\Twitter\Infrastructure\Http\Repository\TweetRepository'  ] ]
