services:
    App\Domain\Subscription\Console\ListMemberSubscriptionsCommand:
        class: 'App\Domain\Subscription\Console\ListMemberSubscriptionsCommand'
        tags:
            - { name: 'console.command' }
        public: true

