services:
    App\Domain\Subscription\Console\ListMemberSubscriptionsCommand:
        class: 'App\Domain\Subscription\Console\ListMemberSubscriptionsCommand'
        calls:
            - [ 'setAccessor', ['@App\Infrastructure\Twitter\Api\Accessor\FriendsListAccessor'] ]
            - [ 'setRepository', ['@App\Infrastructure\Collection\Repository\FriendsListCollectedEventRepository'] ]
        tags:
            - { name: 'console.command' }

    App\Domain\Subscription\Console\UnfollowInactiveMembersCommand:
        class: 'App\Domain\Subscription\Console\UnfollowInactiveMembersCommand'
        calls:
            - [ 'setMutator', [ '@App\Infrastructure\Twitter\Api\Mutator\FriendshipMutator' ] ]
            - [ 'setRepository', [ '@App\Infrastructure\Collection\Repository\FriendsListCollectedEventRepository' ] ]
        tags:
            - { name: 'console.command' }
