services:
    App\Infrastructure\Identification\WhispererIdentification:
        class: 'App\Infrastructure\Identification\WhispererIdentification'
        calls:
            - [ 'setApiAccessor',                           [ '@App\Twitter\Api\Accessor' ] ]
            - [ 'setLikedStatusRepository',                 [ '@repository.liked_status' ] ]
            - [ 'setMemberProfileCollectedEventRepository', [ '@App\Infrastructure\Collection\Repository\MemberProfileCollectedEventRepository' ] ]
            - [ 'setStatusLogger',                          [ '@App\Infrastructure\Log\StatusLogger' ] ]
            - [ 'setStatusRepository',                      [ '@App\Api\Repository\StatusRepository' ] ]
            - [ 'setLogger',                                [ '@logger' ] ]
            - [ 'setTranslator',                            [ '@App\Infrastructure\Translation\Translator' ] ]
            - [ 'setWhispererRepository',                   [ '@repository.whisperer' ] ]