services:
    App\Twitter\Infrastructure\Twitter\Api\Accessor\FollowersListAccessor:
        class: 'App\Twitter\Infrastructure\Twitter\Api\Accessor\FollowersListAccessor'
        arguments:
            - '@App\Twitter\Infrastructure\Api\Accessor'
            - '@logger'
