services:
    App\Twitter\Infrastructure\Twitter\Api\Accessor\FriendsListAccessor:
        class: 'App\Twitter\Infrastructure\Twitter\Api\Accessor\FriendsListAccessor'
        arguments:
            - '@App\Twitter\Infrastructure\Api\Accessor'
            - '@logger'

    App\Twitter\Infrastructure\Twitter\Api\Mutator\FriendshipMutator:
        class: 'App\Twitter\Infrastructure\Twitter\Api\Mutator\FriendshipMutator'
        calls:
            - [ 'setApiAccessor', [ '@App\Twitter\Infrastructure\Api\Accessor' ] ]
            - [ 'setLogger', [ '@logger' ] ]
            - [ 'setMemberRepository', [ '@App\Twitter\Infrastructure\Repository\Membership\MemberRepository' ] ]
