services:
    App\Infrastructure\Twitter\Api\Accessor\FriendsListAccessor:
        class: 'App\Infrastructure\Twitter\Api\Accessor\FriendsListAccessor'
        arguments:
            - '@App\Twitter\Api\Accessor'
            - '@logger'

    App\Infrastructure\Twitter\Api\Mutator\FriendshipMutator:
        class: 'App\Infrastructure\Twitter\Api\Mutator\FriendshipMutator'
        calls:
            - [ 'setApiAccessor', [ '@App\Twitter\Api\Accessor' ] ]
            - [ 'setLogger', [ '@logger' ] ]
            - [ 'setMemberRepository', [ '@App\Infrastructure\Repository\Membership\MemberRepository' ] ]
            - [ 'setMemberSubscriptionRepository', [ '@repository.member_subscription' ] ]

    App\Domain\Subscription\Console\ListMemberSubscriptionsCommand:
        class: 'App\Domain\Subscription\Console\ListMemberSubscriptionsCommand'
        calls:
            - [ 'setAccessor', ['@App\Infrastructure\Twitter\Api\Accessor\FriendsListAccessor'] ]
            - [ 'setRepository', ['@App\Infrastructure\Collection\Repository\FriendsListCollectedEventRepository'] ]
        tags:
            - { name: 'console.command' }

    App\Domain\Subscription\Console\UnfollowInactiveMembersCommand:
        class: 'App\Domain\Subscription\Console\UnfollowInactiveMembersCommand'
        calls:
            - [ 'setMutator', [ '@App\Infrastructure\Twitter\Api\Mutator\FriendshipMutator' ] ]
            - [ 'setListCollectedEventRepository', [ '@App\Infrastructure\Collection\Repository\FriendsListCollectedEventRepository' ] ]
            - [ 'setMemberRepository', [ '@App\Infrastructure\Repository\Membership\MemberRepository' ] ]
        tags:
            - { name: 'console.command' }
