services:
    App\Twitter\Infrastructure\Http\Client\FollowersBatchAwareHttpClient:
        class: 'App\Twitter\Infrastructure\Http\Client\FollowersBatchAwareHttpClient'
        arguments:
            - '@App\Twitter\Domain\Http\Client\HttpClientInterface'
            - '@logger'

    App\Twitter\Infrastructure\Subscription\Console\ListMemberSubscribeesCommand:
        class: 'App\Twitter\Infrastructure\Subscription\Console\ListMemberSubscribeesCommand'
        calls:
            - [ 'setCursorAwareHttpClient', ['@App\Twitter\Infrastructure\Http\Client\FollowersBatchAwareHttpClient'] ]
            - [ 'setRepository',            ['@App\Twitter\Infrastructure\Curation\Repository\FollowersListCollectedEventRepository'] ]
        tags:
            - { name: 'console.command' }
