services:
    App\Twitter\Infrastructure\Identification\WhispererIdentification:
        class: 'App\Twitter\Infrastructure\Identification\WhispererIdentification'
        calls:
            - [ 'setHttpClient',                           [ '@App\Twitter\Domain\Http\Client\HttpClientInterface' ] ]
            - [ 'setMemberProfileCollectedEventRepository', [ '@App\Twitter\Infrastructure\Curation\Repository\MemberProfileCollectedEventRepository' ] ]
            - [ 'setStatusLogger',                          [ '@App\Twitter\Infrastructure\Log\StatusLogger' ] ]
            - [ 'setStatusRepository',                      [ '@App\Twitter\Infrastructure\Http\Repository\StatusRepository' ] ]
            - [ 'setLogger',                                [ '@logger' ] ]
            - [ 'setTranslator',                            [ '@App\Twitter\Infrastructure\Translation\Translator' ] ]
            - [ 'setWhispererRepository',                   [ '@repository.whisperer' ] ]