services:
    App\Membership\Infrastructure\Console\AddMemberToPublishersListCommand:
        class: 'App\Membership\Infrastructure\Console\AddMemberToPublishersListCommand'
        arguments:
            - !php/const 'App\Membership\Infrastructure\Console\AddMemberToPublishersListCommand::COMMAND_NAME'
            - '@App\Membership\Infrastructure\Repository\AggregateSubscriptionRepository'
            - '@App\Membership\Domain\Repository\MemberRepositoryInterface'
            - '@App\Twitter\Infrastructure\Http\Repository\PublishersListRepository'
            - '@App\Twitter\Domain\Http\Client\MembersBatchAwareHttpClientInterface'
            - '@App\Twitter\Domain\Http\Client\ListAwareHttpClientInterface'
            - '@App\Twitter\Domain\Http\Client\TweetAwareHttpClientInterface'
            - '@logger'
        tags:
            - { name: 'console.command' }

    App\Twitter\Infrastructure\Http\Client\FriendsBatchAwareHttpClient:
        class: 'App\Twitter\Infrastructure\Http\Client\FriendsBatchAwareHttpClient'
        arguments:
            - '@App\Twitter\Domain\Http\Client\HttpClientInterface'
            - '@logger'

    App\Twitter\Infrastructure\Http\Mutator\FriendshipMutator:
        class: 'App\Twitter\Infrastructure\Http\Mutator\FriendshipMutator'
        calls:
            - [ 'setHttpClient', [ '@App\Twitter\Domain\Http\Client\HttpClientInterface' ] ]
            - [ 'setLogger', [ '@logger' ] ]
            - [ 'setMemberRepository', [ '@App\Membership\Infrastructure\Repository\MemberRepository' ] ]
            - [ 'setMemberSubscriptionRepository', [ '@repository.member_subscription' ] ]

    App\Twitter\Infrastructure\Subscription\Console\ListMemberSubscriptionsCommand:
        class: 'App\Twitter\Infrastructure\Subscription\Console\ListMemberSubscriptionsCommand'
        calls:
            - [ 'setAccessor',   ['@App\Twitter\Infrastructure\Http\Client\FriendsBatchAwareHttpClient'] ]
            - [ 'setRepository', ['@App\Twitter\Infrastructure\Curation\Repository\FriendsListCollectedEventRepository'] ]
        tags:
            - { name: 'console.command' }

    App\Twitter\Infrastructure\Subscription\Console\UnfollowInactiveMembersCommand:
        class: 'App\Twitter\Infrastructure\Subscription\Console\UnfollowInactiveMembersCommand'
        calls:
            - [ 'setMutator',                       [ '@App\Twitter\Infrastructure\Http\Mutator\FriendshipMutator' ] ]
            - [ 'setListCollectedEventRepository',  [ '@App\Twitter\Infrastructure\Curation\Repository\FriendsListCollectedEventRepository' ] ]
            - [ 'setMemberRepository',              [ '@App\Membership\Infrastructure\Repository\MemberRepository' ] ]
        tags:
            - { name: 'console.command' }

    App\Twitter\Infrastructure\Subscription\Console\ListSubscriptionsToPublishersListsCommand:
        class: 'App\Twitter\Infrastructure\Subscription\Console\ListSubscriptionsToPublishersListsCommand'
        arguments:
            - !php/const 'App\Twitter\Infrastructure\Subscription\Console\ListSubscriptionsToPublishersListsCommand::COMMAND_NAME'
            - '@App\Twitter\Domain\Curation\Repository\ListsBatchCollectedEventRepositoryInterface'
            - '@logger'
        tags:
            - { name: 'console.command' }

    App\Twitter\Infrastructure\PublishersList\Console\ImportMemberPublishersListsCommand:
        class: 'App\Twitter\Infrastructure\PublishersList\Console\ImportMemberPublishersListsCommand'
        arguments:
            - !php/const 'App\Twitter\Infrastructure\PublishersList\Console\ImportMemberPublishersListsCommand::COMMAND_NAME'
            - '@App\Twitter\Domain\Http\Client\HttpClientInterface'
            - '@App\Twitter\Domain\Http\Client\ListAwareHttpClientInterface'
            - '@App\Membership\Domain\Repository\PublishersListSubscriptionRepositoryInterface'
            - '@App\Twitter\Infrastructure\PublishersList\Repository\MemberAggregateSubscriptionRepository'
            - '@App\Membership\Domain\Repository\NetworkRepositoryInterface'
            - '@user_manager'
            - '@logger'
        calls:
            - [ 'setOwnershipBatchCollectedEventRepository',  [ '@App\Twitter\Infrastructure\Curation\Repository\ListsBatchCollectedEventRepository' ] ]
            - [ 'setPublishersListCollectedEventRepository', [ '@App\Twitter\Infrastructure\Curation\Repository\TwitterListCollectedEventRepository' ] ]
        tags:
            - { name: 'console.command' }
