services:
    monolog.json_formatter:
        class:                                  'Monolog\Formatter\JsonFormatter'

    App\Twitter\Infrastructure\Api\Repository\TokenTypeRepository:
        class: App\Twitter\Infrastructure\Api\Repository\TokenTypeRepository
        arguments:
            - '@Doctrine\Common\Persistence\ManagerRegistry'
            - 'App\Twitter\Infrastructure\Api\Entity\TokenType'
        calls:
            - [ 'setLogger', [ '@monolog.logger.doctrine' ]]
        tags:
            - { name: 'doctrine.repository_service' }

    App\Twitter\Domain\Api\Repository\TokenTypeRepositoryInterface: '@App\Twitter\Infrastructure\Api\Repository\TokenTypeRepository'

    App\Twitter\Domain\Api\AccessToken\Repository\TokenRepositoryInterface: '@App\Twitter\Infrastructure\Api\AccessToken\Repository\TokenRepository'
