services:

    App\Twitter\Infrastructure\Publication\Persistence\PublicationPersistence:
        class: 'App\Twitter\Infrastructure\Publication\Persistence\PublicationPersistence'
        arguments:
            - '@App\Twitter\Infrastructure\Publication\Persistence\StatusPersistence'
            - '@App\Twitter\Infrastructure\Publication\Repository\PublicationRepository'
            - '@user_manager'
            - '@doctrine.orm.entity_manager'
        calls:
            - [ 'setStatusPersistence', [ '@App\Twitter\Infrastructure\Publication\Persistence\StatusPersistence' ] ]
        public: true

    App\Twitter\Infrastructure\Publication\Persistence\StatusPersistence:
        class: 'App\Twitter\Infrastructure\Publication\Persistence\StatusPersistence'
        arguments:
            - '@repository.timely_status'
            - '@doctrine'
            - '@doctrine.orm.entity_manager'
            - '@logger'
        calls:
            - [ 'setHttpClient',               [ '@App\Twitter\Domain\Http\Client\HttpClientInterface' ] ]
            - [ 'setLogger',                   [ '@logger' ] ]
            - [ 'setPublishersListRepository', [ '@App\Twitter\Infrastructure\Http\Repository\PublishersListRepository' ] ]
            - [ 'setPublicationPersistence',   [ '@App\Twitter\Infrastructure\Publication\Persistence\PublicationPersistence' ] ]
            - [ 'setTweetCurationLogger',      [ '@App\Twitter\Infrastructure\Log\TweetCurationLogger' ] ]
            - [ 'setStatusRepository',         [ '@App\Twitter\Infrastructure\Http\Repository\TweetRepository' ] ]
            - [ 'setTaggedTweetRepository',    [ '@App\Twitter\Infrastructure\Repository\Status\TaggedTweetRepository' ] ]
        public: true
