services:

    App\Twitter\Infrastructure\Persistence\PersistenceLayer:
        class: 'App\Twitter\Infrastructure\Persistence\PersistenceLayer'
        arguments:
            - '@App\Twitter\Domain\Persistence\TweetPersistenceLayerInterface'
            - '@App\Twitter\Infrastructure\Publication\Repository\TweetPublicationPersistenceLayer'
            - '@user_manager'
            - '@doctrine.orm.entity_manager'
        calls:
            - [ 'setTweetPersistenceLayer', [ '@App\Twitter\Domain\Persistence\TweetPersistenceLayerInterface' ] ]
        public: true

    App\Twitter\Domain\Persistence\PersistenceLayerInterface:
        '@App\Twitter\Infrastructure\Persistence\PersistenceLayer'

    App\Twitter\Infrastructure\Persistence\TweetPersistenceLayer:
        class: 'App\Twitter\Infrastructure\Persistence\TweetPersistenceLayer'
        arguments:
            - '@repository.timely_status'
            - '@doctrine'
            - '@doctrine.orm.entity_manager'
            - '@logger'
        calls:
            - [ 'setHttpClient',               [ '@App\Twitter\Domain\Http\Client\HttpClientInterface' ] ]
            - [ 'setLogger',                   [ '@logger' ] ]
            - [ 'setPublishersListRepository', [ '@App\Twitter\Infrastructure\Http\Repository\PublishersListRepository' ] ]
            - [ 'setPersistenceLayer',   [ '@App\Twitter\Domain\Persistence\PersistenceLayerInterface' ] ]
            - [ 'setTweetCurationLogger',      [ '@App\Twitter\Infrastructure\Log\TweetCurationLogger' ] ]
            - [ 'setTweetRepository',         [ '@App\Twitter\Infrastructure\Http\Repository\TweetRepository' ] ]
            - [ 'setTaggedTweetRepository',    [ '@App\Twitter\Infrastructure\Repository\Status\TaggedTweetRepository' ] ]
        public: true

    App\Twitter\Domain\Persistence\TweetPersistenceLayerInterface:
        '@App\Twitter\Infrastructure\Persistence\TweetPersistenceLayer'
