services:
    app.token_authenticator:
        class: 'App\Twitter\Infrastructure\Security\Authentication\TokenAuthenticator'
        calls:
            - [ 'setMemberRepository', [ '@App\Twitter\Infrastructure\Repository\Membership\MemberRepository' ] ]
