services:
    App\Infrastructure\Amqp\MessageBus\PublicationListDispatcher:
        class: 'App\Infrastructure\Amqp\MessageBus\PublicationListDispatcher'
        calls:
            - [ 'setPublicationListRepository', [ '@App\Infrastructure\Api\Repository\PublicationListRepository' ] ]
            - [ 'setMessageBus',                [ '@messenger.default_bus' ] ]