imports:
    - { resource: config.yml }

parameters:
    main_log_level:     'debug'
    sentry_log_level:   'error'

monolog:
    channels:
        - 'twitter_api'
        - 'status'
        - 'development'
    handlers:
        main:       "%monolog_main_logging_handler%"
        datadog:    "%monolog_monitoring_logging_handler%"
