imports:
    - { resource: config_dev.yml }
    - { resource: ../parameters_test.yml }

parameters:
    main_log_level:     'debug'

framework:
    test:           ~
    session:
        storage_id: session.storage.mock_file

services:
    test.security.authentication.listener.guard:
        alias: security.authentication.listener.guard

    test.security.authentication.manager:
        alias: security.authentication.manager
