imports:
    - { resource: ../extensions/dbal.yml }
    - { resource: ../extensions/messaging.yml }
    - { resource: ../parameters.yml }
    - { resource: ../extensions/security.yml }
    - { resource: ../services.yml }

framework:
    csrf_protection:          true
    default_locale:           "%locale%"
    esi:                      { enabled:     true }
    form:                     true
    fragments:                { path:     /_fragment }
    secret:                   "%framework_secret%"
    router:
        resource:             "%kernel.root_dir%/config/routing/routing.yml"
        strict_requirements:  "%kernel.debug%"
    session:    
        save_path:            "%kernel.root_dir%/var/sessions"
    templating:               { engines:     ['twig'] }
    trusted_proxies:          [127.0.0.1]
    translator:               { fallback:     en }
    validation:               { enable_annotations:     true }

sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }

parameters:
    basic_auth_pattern: /this-route-is-undefined-in-production
    rabbitmq.host:      vagrant-valhalla
    rabbitmq.port:      5672
    rabbitmq.vhost:     weaving_the_web
