parameters:
    weaving_the_web_dashboard.dbal_connection.class: 'WeavingTheWeb\Bundle\DashboardBundle\DBAL\Connection'
    weaving_the_web_dashboard.query_validator.class: 'WeavingTheWeb\Bundle\DashboardBundle\Validator\Constraints\QueryValidator'

services:
    weaving_the_web_dashboard.dbal_connection:
        class:  '%weaving_the_web_dashboard.dbal_connection.class%'
        arguments:
            - '@validator'
            - '@logger'
        calls:
            - [ 'setCharset', [ '%database_charset%' ] ]
            - [ 'setHost', [ '%database_host%' ] ]
            - [ 'setUsername', [ '%database_user%' ] ]
            - [ 'setPassword', [ '%database_password%' ] ]
            - [ 'setPort', [ '%database_port%' ] ]
            - [ 'setDatabase', [ '%database_name%' ] ]
            - [ 'setEntityManager', [ '@doctrine.orm.entity_manager' ] ]
            - [ 'setTranslator', [ '@translator' ] ]

    weaving_the_web_dashboard.query_validator:
        class: '%weaving_the_web_dashboard.query_validator.class%'
        calls:
            - [ 'setTranslator', [ '@translator' ] ]
        tags:
            - { name: 'validator.constraint_validator', alias: 'weaving_the_web.validator.query' }

    twig.extension.text:
        class: 'Twig_Extensions_Extension_Text'
        tags:
            - { name: 'twig.extension' }
