framework:
    cache: ~

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax

    php_errors:
        log: true

    router:
        utf8: true

    secret: '%env(APP_SECRET)%'

    validation:
        email_validation_mode: html5
