framework:
    messenger:
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            # Route your messages to the transports
            'App\Amqp\Message\FetchMemberStatuses': async

services:
    App\Amqp\MessageHandler\FetchMemberStatusesHandler:
        tags:
            -
                name: messenger.message_handler
                handles: App\Amqp\Message\FetchMemberStatuses