framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            news_status:    '%env(MESSENGER_TRANSPORT_DSN_STATUS)%'
            news_likes:     '%env(MESSENGER_TRANSPORT_DSN_LIKES)%'
            failed:         '%env(MESSENGER_TRANSPORT_DSN_FAILURES)%'

        routing:
            # Route your messages to the transports
            'App\Twitter\Infrastructure\Amqp\Message\FetchMemberStatus': news_status
            'App\Twitter\Infrastructure\Amqp\Message\FetchMemberLikes':  news_likes
