framework:
    messenger:
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            news_status: '%env(MESSENGER_TRANSPORT_DSN_STATUS)%'
            news_likes: '%env(MESSENGER_TRANSPORT_DSN_LIKES)%'

        routing:
            # Route your messages to the transports
            'App\Infrastructure\Amqp\Message\FetchMemberStatus': news_status
            'App\Infrastructure\Amqp\Message\FetchMemberLikes':  news_likes
