security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory: { memory: null }
        chain_provider:
            chain:
                providers: [user_provider]
        user_provider:
            entity:
                class:          App\Membership\Domain\Entity\Legacy\Member
                property:       apiKey
                manager_name:   default

    firewalls:
        main:
            anonymous: ~

            logout: ~

            provider: user_provider

            guard:
                authenticators:
                    - app.token_authenticator

            stateless: true

    access_control:
        - { path: ^/api/healthcheck,    role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,                role: ROLE_USER }

