dist: bionic

git:
    depth: 3

language: php

php:
    - '7.4'

services:
    - mysql
    - rabbitmq
    - redis-server

before_install:
    - mysql -e 'CREATE DATABASE test;'
    - ls /home/travis/.phpenv/versions/7.4.0/lib/php/extensions/no-debug-zts-20190902
    - sudo apt -y install librabbitmq-dev
    - echo "extension = amqp" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

after_failure:
    - cat ./var/logs/test.log

install:
    - cp provisioning/continuous-integration/parameters_test.yml.dist .env.test
    - /bin/bash -c 'source ./bin/install-composer.sh'
    - php composer.phar config -g github-oauth.github.com $GITHUB_OAUTH_TOKEN
    - php composer.phar install --prefer-dist --no-scripts
    - php bin/console doctrine:schema:create -n -e test

script:
    - make run-php-unit-tests

cache:
    directories:
        - $HOME/.composer
        - vendor

