callback:
    path:       /api/callback
    controller: App\Trends\Infrastructure\Controller\TrendsController::callback
    methods:    GET|POST|OPTIONS

healthcheck:
    path:       /api/healthcheck
    controller: App\Twitter\Infrastructure\Healthcheck\Controller\HealthcheckController::areServicesHealthy
    methods:    HEAD|GET|OPTIONS

highlight:
    path:       /api/twitter/highlights
    controller: App\Trends\Infrastructure\Controller\TrendsController::getHighlights
    methods:    GET|OPTIONS
