
healthcheck:
    path:     '/api/healthcheck'
    defaults: { _controller: App\Twitter\Infrastructure\Healthcheck\Controller\HealthcheckController::areServicesHealthy }

highlight:
    path:     '/api/twitter/highlights'
    defaults: { _controller: App\Trends\Controller\ListController::getHighlights }
