
healthcheck:
    path:     '/api/healthcheck'
    defaults: { _controller: controller.healthcheck::areServicesHealthy }

highlight:
    path:     '/api/twitter/highlights'
    defaults: { _controller: controller.list::getHighlights }
