parameters:
    database_charset_admin:   "utf8mb4"
    database_driver_admin:    "pdo_mysql"
    database_host_admin:      "%mysql.host%"
    database_port_admin:      "%mysql.port%"
    database_name_admin:      "%mysql.database%"
    database_user_admin:      "%mysql.admin_user%"
    database_password_admin:  "%mysql.admin_password%"

    database_charset:         "utf8mb4"
    database_driver:          "pdo_mysql"
    database_host:            "%mysql.host%"
    database_port:            "%mysql.port%"
    database_name:            "%mysql.database%"
    database_user:            "%mysql.user%"
    database_password:        "%mysql.password%"

    database_charset_read:    "utf8mb4"
    database_driver_read:     "pdo_mysql"
    database_host_read:       "%mysql.host_read%"
    database_port_read:       "%mysql.port_read%"
    database_name_read:       "%mysql.database_read%"
    database_user_read:       "%mysql.user_read%"
    database_password_read:   "%mysql.password_read%"

    database_charset_write:   "utf8mb4"
    database_driver_write:    "pdo_mysql"
    database_host_write:      "%mysql.host_write%"
    database_port_write:      "%mysql.port_write%"
    database_name_write:      "%mysql.database_write%"
    database_user_write:      "%mysql.user_write%"
    database_password_write:  "%mysql.password_write%"

    database_charset_test:    "utf8mb4"
    database_driver_test:     "pdo_mysql"
    database_host_test:       "%mysql.host%"
    database_port_test:       "%mysql.port%"
    database_name_test:       "%mysql.test_database%"
    database_user_test:       "%mysql.test_user%"
    database_password_test:   "%mysql.test_password%"

    it_1: 'header|mail_uid|mailbox|mailbox_mail_uid|mailbox_mail_uid_header|message|message_property'
    it_2: '|property|tmp_news|weaving_arc|weaving_author|weaving_contact|weaving_content|weaving_content_type|'
    it_3: 'weaving_edge|weaving_entity|weaving_entity_table|weaving_entity_type|weaving_event|weaving_facebook*'
    it_4: '|weaving_feed|weaving_feedback|weaving_file|weaving_flag|weaving_form|weaving_github|'
    it_5: 'weaving_insight|weaving_insight_moderation|weaving_insight_node|weaving_insight_sharing|'
    it_6: 'weaving_language|weaving_language_item|weaving_link|weaving_location|weaving_log|'
    it_7: 'weaving_namespace|weaving_outgoing|weaving_perspective|weaving_photograph|weaving_placeholder|'
    it_8: 'weaving_privilege|weaving_query|weaving_recipient|weaving_recipient_list|'
    it_9: 'weaving_route|weaving_serialization|weaving_snapshot|weaving_store|weaving_store_item|weaving_stylesheet|'
    it_10: 'weaving_template|weaving_token|weaving_group'

    schema_filter: "~^(?!%it_1%%it_2%%it_3%%it_4%%it_5%%it_6%%it_7%%it_8%%it_9%%it_10%)~"
