imports:
    - { resource: services/_parameters.yml }
    - { resource: services/console.yml }
    - { resource: services/curation.yml }
    - { resource: services/mapping.yml }
    - { resource: services/member_subscribee.yml }
    - { resource: services/member_subscription.yml }
    - { resource: services/membership.yml }
    - { resource: services/persistence.yml }
    - { resource: services/repository.yml }
    - { resource: services/twitter_api.yml }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    #    App\:
    #        resource: '../src/*'
    #        exclude: '../src/{Controler,DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Twitter\Infrastructure\Log\TweetCurationLogger:
        class: 'App\Twitter\Infrastructure\Log\TweetCurationLogger'
        arguments:
            - '@App\Twitter\Infrastructure\Translation\Translator'
            - '@monolog.logger.twitter_api'

    App\Twitter\Infrastructure\Publication\Formatter\PublicationFormatter:
        public: true
        class: 'App\Twitter\Infrastructure\Publication\Formatter\PublicationFormatter'
        calls:
            - [ 'setTweetAwareHttpClient',   [ '@App\Twitter\Infrastructure\Http\Client\TweetAwareHttpClient' ] ]
            - [ 'setTweetRepository', [ '@App\Twitter\Infrastructure\Http\Repository\TweetRepository' ] ]

    App\Twitter\Infrastructure\Http\Repository\TweetRepository:
        class: 'App\Twitter\Infrastructure\Http\Repository\TweetRepository'
        arguments:
            - '@doctrine'
            - 'App\Twitter\Infrastructure\Http\Entity\Tweet'
        calls:
            - [ 'setMemberRepository',       [ '@user_manager' ] ]
            - [ 'setTweetPublicationPersistenceLayer',  [ '@App\Twitter\Infrastructure\Publication\Repository\TweetPublicationPersistenceLayer' ] ]
            - [ 'setTweetCurationLogger',    [ '@App\Twitter\Infrastructure\Log\TweetCurationLogger' ] ]
            - [ 'setTweetPersistenceLayer',      [ '@App\Twitter\Domain\Persistence\TweetPersistenceLayerInterface' ] ]
            - [ 'setTaggedTweetRepository',  [ '@App\Twitter\Infrastructure\Repository\Status\TaggedTweetRepository' ] ]
            - [ 'setTimelyStatusRepository', [ '@repository.timely_status' ] ]
        properties:
            appLogger:                '@logger'
            archivedTweetRepository:  '@App\Twitter\Infrastructure\Http\Repository\ArchivedTweetRepository'
            connection:               '@doctrine.dbal.default_connection'
            registry:                 '@doctrine'
        tags:
            - { name: 'doctrine.repository_service' }

    App\Twitter\Domain\Publication\Repository\TweetRepositoryInterface: '@App\Twitter\Infrastructure\Http\Repository\TweetRepository'

    App\Twitter\Infrastructure\Http\Repository\ArchivedTweetRepository:
        class: 'App\Twitter\Infrastructure\Http\Repository\ArchivedTweetRepository'
        arguments:
            - '@doctrine'
            - 'App\Twitter\Infrastructure\Http\Entity\ArchivedTweet'
        calls:
            - [ 'setMemberRepository',       [ '@user_manager' ] ]
            - [ 'setPersistenceLayer',       [ '@App\Twitter\Domain\Persistence\PersistenceLayerInterface' ] ]
            - [ 'setTweetPublicationPersistenceLayer',  [ '@App\Twitter\Infrastructure\Publication\Repository\TweetPublicationPersistenceLayer' ] ]
            - [ 'setTweetCurationLogger',    [ '@App\Twitter\Infrastructure\Log\TweetCurationLogger' ] ]
            - [ 'setTaggedTweetRepository',  [ '@App\Twitter\Infrastructure\Repository\Status\TaggedTweetRepository' ] ]
            - [ 'setTimelyStatusRepository', [ '@repository.timely_status' ] ]
        properties:
            appLogger:              '@logger'
            connection:             '@doctrine.dbal.default_connection'
            registry:               '@doctrine'

    app.twitter.repository.read.status:
        class: 'App\Twitter\Infrastructure\Http\Repository\TweetRepository'
        arguments:
            - '@doctrine'
            - 'App\Twitter\Infrastructure\Http\Entity\Tweet'
        calls:
            - [ 'setMemberRepository',       [ '@user_manager' ] ]
            - [ 'setTweetPublicationPersistenceLayer',  [ '@App\Twitter\Infrastructure\Publication\Repository\TweetPublicationPersistenceLayer' ] ]
            - [ 'setTweetCurationLogger',    [ '@App\Twitter\Infrastructure\Log\TweetCurationLogger' ] ]
            - [ 'setTaggedTweetRepository',  [ '@App\Twitter\Infrastructure\Repository\Status\TaggedTweetRepository' ] ]
            - [ 'setTimelyStatusRepository', [ '@repository.timely_status' ] ]
        properties:
            registry:               '@doctrine'
            statusLogger:           '@monolog.logger.twitter_api'
            connection:             '@doctrine.dbal.default_connection'

    App\Twitter\Infrastructure\Amqp\MessageBus\FetchTweetsAmqpMessagesDispatcher:
        class: 'App\Twitter\Infrastructure\Amqp\MessageBus\FetchTweetsAmqpMessagesDispatcher'
        arguments:
            - '@App\Twitter\Domain\Http\Client\HttpClientInterface'
            - '@App\Twitter\Infrastructure\Amqp\ResourceProcessor\PublishersListProcessor'
            - '@App\Twitter\Infrastructure\Http\AccessToken\TokenChange'
            - '@logger'
            - '@App\Twitter\Infrastructure\Translation\Translator'
        calls:
            - [ 'setRateLimitCompliance',                    [ '@App\Twitter\Infrastructure\Http\Compliance\RateLimitCompliance' ] ]
            - [ 'setOwnershipAccessor',                      [ '@App\Twitter\Domain\Http\Client\ListAwareHttpClientInterface' ] ]
            - [ 'setListsBatchCollectedEventRepository', [ '@App\Twitter\Infrastructure\Curation\Repository\ListsBatchCollectedEventRepository' ] ]

    App\Twitter\Infrastructure\Amqp\ResourceProcessor\MemberIdentityProcessor:
        class: 'App\Twitter\Infrastructure\Amqp\ResourceProcessor\MemberIdentityProcessor'
        arguments:
            - '@messenger.default_bus'
            - '@App\Twitter\Infrastructure\Http\Client\MemberProfileAwareHttpClient'
            - '@App\Twitter\Infrastructure\Http\Repository\PublishersListRepository'
            - '@logger'

    App\Twitter\Infrastructure\Amqp\ResourceProcessor\PublishersListProcessor:
        class: 'App\Twitter\Infrastructure\Amqp\ResourceProcessor\PublishersListProcessor'
        calls:
            - [ 'setMemberIdentityProcessor',                 [ '@App\Twitter\Infrastructure\Amqp\ResourceProcessor\MemberIdentityProcessor'] ]
            - [ 'setMemberProfileCollectedEventRepository',   [ '@App\Twitter\Infrastructure\Curation\Repository\MemberProfileCollectedEventRepository'] ]
            - [ 'setPublishersListCollectedEventRepository', [ '@App\Twitter\Infrastructure\Curation\Repository\TwitterListCollectedEventRepository'] ]
            - [ 'setTokenChange',                             [ '@App\Twitter\Infrastructure\Http\AccessToken\TokenChange'] ]
        arguments:
            - '@App\Twitter\Domain\Http\Client\HttpClientInterface'
            - '@App\Twitter\Infrastructure\Translation\Translator'
            - '@logger'

    App\Twitter\Infrastructure\Http\UnavailableResourceHandler:
        class: 'App\Twitter\Infrastructure\Http\UnavailableResourceHandler'
        arguments:
            - '@user_manager'
            - '@logger'

    App\Twitter\Infrastructure\Repository\Status\TaggedTweetRepository:
        class: 'App\Twitter\Infrastructure\Repository\Status\TaggedTweetRepository'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@logger'
        calls:
            - [ 'setTweetRepository', [ '@App\Twitter\Domain\Publication\Repository\TweetRepositoryInterface' ] ]

    App\Twitter\Infrastructure\Http\Client\HttpClient:
        class: 'App\Twitter\Infrastructure\Http\Client\HttpClient'
        arguments:
            - '%app.twitter_api.consumer_key%'
            - '%app.twitter_api.consumer_secret%'
            - '%app.twitter.oauth_token.default%'
            - '%app.twitter.oauth_secret.default%'
            - '@App\Twitter\Domain\Http\AccessToken\Repository\TokenRepositoryInterface'
            - '@monolog.logger.twitter_api'
        properties:
            environment:            '%kernel.environment%'
            tweetAwareHttpClient:   '@App\Twitter\Infrastructure\Http\Client\TweetAwareHttpClient'
            twitterApiLogger:       '@monolog.logger.twitter_api'
        calls:
            - [ 'setConsumerKey', [ '%app.twitter_api.consumer_key%' ] ]
            - [ 'setConsumerSecret', [ '%app.twitter_api.consumer_secret%' ] ]
            - [ 'setMemberRepository', [ '@user_manager' ] ]
            - [ 'setRateLimitCompliance', [ '@App\Twitter\Infrastructure\Http\Compliance\RateLimitCompliance' ] ]
            - [ 'setTranslator', [ '@App\Twitter\Infrastructure\Translation\Translator' ] ]
            - [ 'setAccessToken', [ '%app.twitter.oauth_token.default%' ] ]
            - [ 'setAccessTokenSecret', [ '%app.twitter.oauth_secret.default%' ] ]

    App\Twitter\Domain\Http\Client\HttpClientInterface: '@App\Twitter\Infrastructure\Http\Client\HttpClient'

    App\Twitter\Infrastructure\Http\Client\TweetAwareHttpClient:
        class: 'App\Twitter\Infrastructure\Http\Client\TweetAwareHttpClient'
        properties:
            archivedTweetRepository: '@App\Twitter\Infrastructure\Http\Repository\ArchivedTweetRepository'
            entityManager:              '@doctrine.orm.entity_manager'
            notFoundtweetRepository:   '@repository.not_found_status'
        calls:
            - [ 'setHttpClient',                               [ '@App\Twitter\Infrastructure\Http\Client\HttpClient' ] ]
            - [ 'setLogger',                                    [ '@logger' ] ]
            - [ 'setMemberRepository',                          [ '@App\Membership\Infrastructure\Repository\MemberRepository' ] ]
            - [ 'setMemberProfileCollectedEventRepository',     [ '@App\Twitter\Infrastructure\Curation\Repository\MemberProfileCollectedEventRepository' ] ]
            - [ 'setPersistenceLayer',                    [ '@App\Twitter\Domain\Persistence\PersistenceLayerInterface' ] ]
            - [ 'setTweetRepository',                          [ '@App\Twitter\Infrastructure\Http\Repository\TweetRepository' ] ]
            - [ 'setTweetsBatchCollectedEventRepository',  [ '@App\Twitter\Infrastructure\Curation\Repository\TweetsBatchCollectedEventRepository' ] ]
        public: true

    App\Twitter\Domain\Http\Client\TweetAwareHttpClientInterface: '@App\Twitter\Infrastructure\Http\Client\TweetAwareHttpClient'

    app.event_subscriber.console:
        class: 'App\Twitter\Infrastructure\Console\EventSubscriber\ConsoleEventsSubscriber'
        properties:
            logger: '@logger'
        tags:
            - { name: 'kernel.event_subscriber' }

    App\Twitter\Infrastructure\Http\Compliance\RateLimitCompliance:
        class: 'App\Twitter\Infrastructure\Http\Compliance\RateLimitCompliance'
        arguments:
            - '@?logger'

    App\Twitter\Infrastructure\Curation\TweetCurator:
        class: 'App\Twitter\Infrastructure\Curation\TweetCurator'
        calls:
            - [ 'setHttpClient',                            [ '@App\Twitter\Infrastructure\Http\Client\HttpClient' ] ]
            - [ 'setInterruptibleCurator',                  [ '@App\Twitter\Infrastructure\Curation\InterruptibleCurator' ] ]
            - [ 'setLogger',                                [ '@monolog.logger.twitter_api' ] ]
            - [ 'setMemberProfileCollectedEventRepository', [ '@App\Twitter\Infrastructure\Curation\Repository\MemberProfileCollectedEventRepository' ] ]
            - [ 'setMemberRepository',                      [ '@App\Membership\Infrastructure\Repository\MemberRepository' ] ]
            - [ 'setPersistenceLayer',                      [ '@App\Twitter\Domain\Persistence\PersistenceLayerInterface' ] ]
            - [ 'setTweetPersistenceLayer',                 [ '@App\Twitter\Domain\Persistence\TweetPersistenceLayerInterface' ] ]
            - [ 'setPublishersListRepository',              [ '@App\Twitter\Infrastructure\Http\Repository\PublishersListRepository' ] ]
            - [ 'setRateLimitCompliance',                   [ '@App\Twitter\Infrastructure\Http\Compliance\RateLimitCompliance' ] ]
            - [ 'setTweetsBatchCollectedEventRepository',   [ '@App\Twitter\Infrastructure\Curation\Repository\TweetsBatchCollectedEventRepository' ] ]
            - [ 'setTweetCurationLogger',                   [ '@App\Twitter\Infrastructure\Log\TweetCurationLogger' ] ]
            - [ 'setTweetAwareHttpClient',                  [ '@App\Twitter\Infrastructure\Http\Client\TweetAwareHttpClient' ] ]
            - [ 'setTweetRepository',                      [ '@App\Twitter\Infrastructure\Http\Repository\TweetRepository' ] ]
            - [ 'setTokenRepository',                       [ '@App\Twitter\Domain\Http\AccessToken\Repository\TokenRepositoryInterface' ] ]
            - [ 'setTranslator',                            [ '@App\Twitter\Infrastructure\Translation\Translator' ] ]
            - [ 'setWhispererIdentification',               [ '@App\Twitter\Infrastructure\Identification\WhispererIdentification' ] ]
            - [ 'setWhispererRepository',                   [ '@repository.whisperer' ] ]
        properties:
            twitterApiLogger:                                   '@monolog.logger.twitter_api'

    App\Twitter\Domain\Curation\Curator\TweetCuratorInterface:
        '@App\Twitter\Infrastructure\Curation\TweetCurator'

    App\Twitter\Infrastructure\Translation\Translator:
        class: 'App\Twitter\Infrastructure\Translation\Translator'
        arguments:
            - '@translator'
            - '@logger'
