services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    test.event_repository.member_profile_collected: '@App\Twitter\Infrastructure\Curation\Repository\MemberProfileCollectedEventRepository'

    test.App\Twitter\Infrastructure\Amqp\MessageBus\FetchTweetsMessageDispatcher: '@App\Twitter\Infrastructure\Amqp\MessageBus\FetchTweetsMessageDispatcher'

    test.App\Twitter\Infrastructure\Subscription\Console\ListMemberSubscriptionsCommand: '@App\Twitter\Infrastructure\Subscription\Console\ListMemberSubscriptionsCommand'
    test.App\Twitter\Infrastructure\Subscription\Console\ListMemberSubscribeesCommand: '@App\Twitter\Infrastructure\Subscription\Console\ListMemberSubscribeesCommand'
    test.App\Twitter\Infrastructure\Subscription\Console\UnfollowDiffSubscriptionsSubscribeesCommand: '@App\Twitter\Infrastructure\Subscription\Console\UnfollowDiffSubscriptionsSubscribeesCommand'
    test.App\Twitter\Infrastructure\Subscription\Console\UnfollowInactiveMembersCommand: '@App\Twitter\Infrastructure\Subscription\Console\UnfollowInactiveMembersCommand'
    test.App\Twitter\Infrastructure\Api\Security\Authorization\Console\AuthorizeApplicationCommand: '@App\Twitter\Infrastructure\Api\Security\Authorization\Console\AuthorizeApplicationCommand'

    App\Twitter\Domain\Api\Accessor\MemberProfileAccessorInterface:
        factory: [ 'App\Tests\Twitter\Infrastructure\Api\Builder\Accessor\MemberProfileAccessorBuilder', 'build' ]

    test.App\Twitter\Domain\Membership\Repository\MemberRepositoryInterface: '@App\Twitter\Domain\Membership\Repository\MemberRepositoryInterface'
    test.App\Twitter\Domain\Api\AccessToken\Repository\TokenRepositoryInterface: '@App\Twitter\Domain\Api\AccessToken\Repository\TokenRepositoryInterface'
    test.App\Twitter\Infrastructure\Curation\Repository\OwnershipBatchCollectedEventRepository: '@App\Twitter\Infrastructure\Curation\Repository\OwnershipBatchCollectedEventRepository'
    test.App\Twitter\Infrastructure\Curation\Repository\FriendsListCollectedEventRepository: '@App\Twitter\Infrastructure\Curation\Repository\FriendsListCollectedEventRepository'
    test.App\Twitter\Infrastructure\Curation\Repository\FollowersListCollectedEventRepository: '@App\Twitter\Infrastructure\Curation\Repository\FollowersListCollectedEventRepository'

    App\Twitter\Infrastructure\Api\Security\Authorization\AuthorizeAccess:
        factory: ['App\Tests\Twitter\Infrastructure\Api\Security\Authorization\Builder\AuthorizeAccessBuilder', 'build']

    App\Twitter\Domain\Api\Accessor\ApiAccessorInterface:
        factory: ['App\Tests\Twitter\Infrastructure\Api\Builder\Accessor\ApiAccessorBuilder', 'willAllowPublishersListToBeImportedForMemberHavingScreenName']
        arguments:
            - '@App\Twitter\Domain\Membership\Repository\MemberRepositoryInterface'
            - '@logger'
            - !php/const 'App\Tests\Twitter\Infrastructure\PublishersList\Console\ImportMemberPublishersListsCommandTest::SCREEN_NAME'

    App\Twitter\Domain\Api\Accessor\OwnershipAccessorInterface:
        factory: ['App\Tests\Twitter\Infrastructure\Api\Builder\Accessor\OwnershipAccessorBuilder', 'willAllowPublishersListToBeImportedForMemberHavingScreenName']

    App\Twitter\Domain\Api\Accessor\StatusAccessorInterface:
        factory: ['App\Tests\Twitter\Infrastructure\Api\Builder\Accessor\StatusAccessorBuilder', 'willEnsureMemberHavingNameExists']
        arguments:
            - '@App\Twitter\Domain\Membership\Repository\MemberRepositoryInterface'

    App\Twitter\Domain\Api\Accessor\MembersListAccessorInterface:
        factory: ['App\Tests\Twitter\Infrastructure\Api\Builder\Accessor\MembersListAccessorBuilder', 'willAddMembersToList']

    App\Membership\Domain\Repository\NetworkRepositoryInterface:
        factory: ['App\Tests\Membership\Builder\Repository\NetworkRepositoryBuilder', 'build']
        arguments:
            - '@App\Twitter\Domain\Membership\Repository\MemberRepositoryInterface'
            - '@logger'

    test.App\Membership\Infrastructure\Console\AddMemberToPublishersListCommand:
        '@App\Membership\Infrastructure\Console\AddMemberToPublishersListCommand'

    test.App\Twitter\Infrastructure\PublishersList\Console\ImportMemberPublishersListsCommand:
        '@App\Twitter\Infrastructure\PublishersList\Console\ImportMemberPublishersListsCommand'

    test.App\Twitter\Infrastructure\Subscription\Console\ListSubscriptionsToPublishersListsCommand:
        '@App\Twitter\Infrastructure\Subscription\Console\ListSubscriptionsToPublishersListsCommand'

    test.App\Twitter\Domain\Curation\Repository\OwnershipBatchCollectedEventRepositoryInterface:
        '@App\Twitter\Domain\Curation\Repository\OwnershipBatchCollectedEventRepositoryInterface'
