imports:
    - { resource: services/api.yml }
    - { resource: services/collection.yml }
    - { resource: services/command.yml }
    - { resource: services/controller.yml }
    - { resource: services/mapping.yml }
    - { resource: services/membership.yml }
    - { resource: services/member_subscribee.yml }
    - { resource: services/member_subscription.yml }
    - { resource: services/operation.yml }
    - { resource: services/repository.yml }
    - { resource: services/persistence.yml }
    - { resource: services/security.yml }
    - { resource: services/worker.yml }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    #    App\:
    #        resource: '../src/*'
    #        exclude: '../src/{Controler,DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Aggregate/Controller/.*.php'
        tags: ['controller.service_arguments']

    App\Infrastructure\Log\StatusLogger:
        class: 'App\Infrastructure\Log\StatusLogger'
        arguments:
            - '@App\Infrastructure\Translation\Translator'
            - '@monolog.logger.status'

    App\Infrastructure\Status\Formatter\PublicationFormatter:
        public: true
        class: 'App\Infrastructure\Status\Formatter\PublicationFormatter'
        calls:
            - [ 'setStatusAccessor',   [ '@App\Accessor\StatusAccessor' ] ]
            - [ 'setStatusRepository', [ '@App\Api\Repository\StatusRepository' ] ]

    App\Api\Repository\StatusRepository:
        class:  '\App\Api\Repository\StatusRepository'
        arguments:
            - '@Doctrine\Common\Persistence\ManagerRegistry'
            - '%weaving_the_web_twitter.entity.status.class%'
        calls:
            - [ 'setMemberRepository',       [ '@user_manager' ] ]
            - [ 'setPublicationRepository',  [ '@App\Twitter\Repository\PublicationRepository' ] ]
            - [ 'setStatusLogger',           [ '@App\Infrastructure\Log\StatusLogger' ] ]
            - [ 'setStatusPersistence',      [ '@App\Infrastructure\Status\Persistence\StatusPersistence' ] ]
            - [ 'setTaggedStatusRepository', [ '@App\Infrastructure\Repository\Status\TaggedStatusRepository' ] ]
            - [ 'setTimelyStatusRepository', [ '@repository.timely_status' ] ]
        properties:
            appLogger:                '@logger'
            archivedStatusRepository: '@App\Api\Repository\ArchivedStatusRepository'
            connection:               '@doctrine.dbal.default_connection'
            likedStatusRepository:    '@repository.liked_status'
            registry:                 '@doctrine'

    App\Api\Repository\ArchivedStatusRepository:
        class:  '\App\Api\Repository\ArchivedStatusRepository'
        arguments:
            - '@Doctrine\Common\Persistence\ManagerRegistry'
            - '%weaving_the_web_twitter.entity.archived_status.class%'
        calls:
            - [ 'setMemberRepository',       [ '@user_manager' ] ]
            - [ 'setPublicationRepository',  [ '@App\Twitter\Repository\PublicationRepository' ] ]
            - [ 'setStatusLogger',           [ '@App\Infrastructure\Log\StatusLogger' ] ]
            - [ 'setStatusPersistence',      [ '@App\Infrastructure\Status\Persistence\StatusPersistence' ] ]
            - [ 'setTaggedStatusRepository', [ '@App\Infrastructure\Repository\Status\TaggedStatusRepository' ] ]
            - [ 'setTimelyStatusRepository', [ '@repository.timely_status' ] ]
        properties:
            appLogger:              '@logger'
            connection:             '@doctrine.dbal.default_connection'
            likedStatusRepository:  '@repository.liked_status'
            registry:               '@doctrine'

    weaving_the_web_twitter.repository.read.status:
        class:  'App\Api\Repository\StatusRepository'
        arguments:
            - '@Doctrine\Common\Persistence\ManagerRegistry'
            - '%weaving_the_web_twitter.entity.status.class%'
        calls:
            - [ 'setOauthTokens',            [ [ '%weaving_the_web_twitter.oauth_token.default%' ] ] ]
            - [ 'setMemberRepository',       [ '@user_manager' ] ]
            - [ 'setPublicationRepository',  [ '@App\Twitter\Repository\PublicationRepository' ] ]
            - [ 'setStatusLogger',           [ '@App\Infrastructure\Log\StatusLogger' ] ]
            - [ 'setTaggedStatusRepository', [ '@App\Infrastructure\Repository\Status\TaggedStatusRepository' ] ]
            - [ 'setTimelyStatusRepository', [ '@repository.timely_status' ] ]
        properties:
            likedStatusRepository:  '@repository.liked_status'
            registry:               '@doctrine'
            statusLogger:           '@monolog.logger.status'
            connection:             '@doctrine.dbal.default_connection'

    App\Infrastructure\Amqp\ResourceProcessor\MemberIdentityProcessor:
        class: 'App\Infrastructure\Amqp\ResourceProcessor\MemberIdentityProcessor'
        arguments:
            - '@messenger.default_bus'
            - '@App\Infrastructure\Twitter\Api\Accessor\MemberProfileAccessor'
            - '@App\Api\Repository\PublicationListRepository'
            - '@logger'

    App\Infrastructure\Amqp\ResourceProcessor\PublicationListProcessor:
        class: 'App\Infrastructure\Amqp\ResourceProcessor\PublicationListProcessor'
        calls:
            - [ 'setMemberIdentityProcessor',                 [ '@App\Infrastructure\Amqp\ResourceProcessor\MemberIdentityProcessor'] ]
            - [ 'setMemberProfileCollectedEventRepository',   [ '@App\Infrastructure\Collection\Repository\MemberProfileCollectedEventRepository'] ]
            - [ 'setPublicationListCollectedEventRepository', [ '@App\Infrastructure\Collection\Repository\PublicationListCollectedEventRepository'] ]
            - [ 'setTokenChange',                             [ '@App\Api\AccessToken\TokenChange'] ]
        arguments:
            - '@App\Twitter\Api\Accessor'
            - '@App\Infrastructure\Translation\Translator'
            - '@logger'

    App\Infrastructure\Amqp\MessageBus\PublicationMessageDispatcher:
        class: 'App\Infrastructure\Amqp\MessageBus\PublicationMessageDispatcher'
        arguments:
            - '@App\Twitter\Api\Accessor'
            - '@App\Infrastructure\Amqp\ResourceProcessor\PublicationListProcessor'
            - '@App\Api\AccessToken\TokenChange'
            - '@logger'
            - '@App\Infrastructure\Translation\Translator'
        calls:
            - [ 'setModerator',                              [ '@App\Api\Moderator\ApiLimitModerator' ] ]
            - [ 'setOwnershipAccessor',                      [ '@App\Infrastructure\Twitter\Api\Accessor\OwnershipAccessor' ] ]
            - [ 'setOwnershipBatchCollectedEventRepository', [ '@App\Infrastructure\Collection\Repository\OwnershipBatchCollectedEventRepository' ] ]

    App\Infrastructure\Twitter\Api\UnavailableResourceHandler:
        class: 'App\Infrastructure\Twitter\Api\UnavailableResourceHandler'
        arguments:
            - '@user_manager'
            - '@logger'

    App\Infrastructure\Repository\Status\TaggedStatusRepository:
        class: 'App\Infrastructure\Repository\Status\TaggedStatusRepository'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@logger'

    App\Twitter\Api\Accessor:
        class: 'App\Twitter\Api\Accessor'
        arguments:
            - '%weaving_the_web_twitter.consumer_key%'
            - '%weaving_the_web_twitter.consumer_secret%'
            - '%weaving_the_web_twitter.oauth_token.default%'
            - '%weaving_the_web_twitter.oauth_secret.default%'
            - '@repository.access_token'
            - '@logger'
        properties:
            environment:          '%kernel.environment%'
            twitterApiLogger:     '@monolog.logger.twitter_api'
            statusAccessor:       '@App\Accessor\StatusAccessor'
        calls:
            - [ 'setClientClass', [ '\Goutte\Client' ] ]
            - [ 'setConsumerKey', [ '%weaving_the_web_twitter.consumer_key%' ] ]
            - [ 'setConsumerSecret', [ '%weaving_the_web_twitter.consumer_secret%' ] ]
            - [ 'setMemberRepository', [ '@user_manager' ] ]
            - [ 'setModerator', [ '@App\Api\Moderator\ApiLimitModerator' ] ]
            - [ 'setTranslator', [ '@App\Infrastructure\Translation\Translator' ] ]
            - [ 'setUserSecret', [ '%weaving_the_web_twitter.oauth_secret.default%' ] ]
            - [ 'setUserToken', [ '%weaving_the_web_twitter.oauth_token.default%' ] ]

    App\Accessor\StatusAccessor:
        class: 'App\Accessor\StatusAccessor'
        properties:
            archivedStatusRepository:   '@App\Api\Repository\ArchivedStatusRepository'
            entityManager:              '@doctrine.orm.entity_manager'
            notFoundStatusRepository:   '@repository.not_found_status'
        calls:
            - [ 'setApiAccessor',                               [ '@App\Twitter\Api\Accessor' ] ]
            - [ 'setLogger',                                    [ '@logger' ] ]
            - [ 'setLikedStatusRepository',                     [ '@repository.liked_status' ] ]
            - [ 'setMemberRepository',                          [ '@App\Infrastructure\Repository\Membership\MemberRepository' ] ]
            - [ 'setMemberProfileCollectedEventRepository',     [ '@App\Infrastructure\Collection\Repository\MemberProfileCollectedEventRepository' ] ]
            - [ 'setPublicationPersistence',                    [ '@App\Infrastructure\Status\Persistence\PublicationPersistence' ] ]
            - [ 'setStatusRepository',                          [ '@App\Api\Repository\StatusRepository' ] ]
            - [ 'setPublicationBatchCollectedEventRepository',  [ '@App\Infrastructure\Collection\Repository\PublicationBatchCollectedEventRepository' ] ]
        public: true

    app.cache.redis:
        class: '%redis_cache%'
        arguments:
            - "%redis_host%"
            - "%redis_port%"

    app.authenticator:
        class: 'App\Member\Authentication\Authenticator'
        properties:
            authenticationTokenRepository:  '@repository.authentication_token'
            authorizedIss:                  '%authorized_iss%'
            validAudience:                  '%valid_audience%'

    app.event_subscriber.console:
        class: 'App\Console\EventSubscriber\ConsoleEventsSubscriber'
        properties:
            logger: '@logger'
        tags:
            - { name: 'kernel.event_subscriber' }

    App\Api\Moderator\ApiLimitModerator:
        class:  'App\Api\Moderator\ApiLimitModerator'
        arguments:
            - '@?logger'

    App\Infrastructure\Twitter\Collector\PublicationCollector:
        class:  'App\Infrastructure\Twitter\Collector\PublicationCollector'
        calls:
            - [ 'setApiAccessor',                               [ '@App\Twitter\Api\Accessor' ] ]
            - [ 'setInterruptibleCollectDeciderInterface',      [ '@App\Infrastructure\Twitter\Collector\InterruptibleCollectDecider' ] ]
            - [ 'setLogger',                                    [ '@monolog.logger.status' ] ]
            - [ 'setLikedStatusRepository',                     [ '@repository.liked_status' ] ]
            - [ 'setMemberProfileCollectedEventRepository',     [ '@App\Infrastructure\Collection\Repository\MemberProfileCollectedEventRepository' ] ]
            - [ 'setMemberRepository',                          [ '@App\Infrastructure\Repository\Membership\MemberRepository' ] ]
            - [ 'setModerator',                                 [ '@App\Api\Moderator\ApiLimitModerator' ] ]
            - [ 'setPublicationBatchCollectedEventRepository',  [ '@App\Infrastructure\Collection\Repository\PublicationBatchCollectedEventRepository' ] ]
            - [ 'setPublicationListRepository',                 [ '@App\Api\Repository\PublicationListRepository' ] ]
            - [ 'setPublicationPersistence',                    [ '@App\Infrastructure\Status\Persistence\PublicationPersistence' ] ]
            - [ 'setStatusLogger',                              [ '@App\Infrastructure\Log\StatusLogger' ] ]
            - [ 'setStatusAccessor',                            [ '@App\Accessor\StatusAccessor' ] ]
            - [ 'setStatusRepository',                          [ '@App\Api\Repository\StatusRepository' ] ]
            - [ 'setStatusPersistence',                         [ '@App\Infrastructure\Status\Persistence\StatusPersistence' ] ]
            - [ 'setTokenRepository',                           [ '@repository.access_token' ] ]
            - [ 'setTranslator',                                [ '@App\Infrastructure\Translation\Translator' ] ]
            - [ 'setWhispererIdentification',                   [ '@App\Infrastructure\Identification\WhispererIdentification' ] ]
            - [ 'setWhispererRepository',                       [ '@repository.whisperer' ] ]
        properties:
            twitterApiLogger:       '@monolog.logger.twitter_api'

    App\Infrastructure\Translation\Translator:
        class: 'App\Infrastructure\Translation\Translator'
        arguments:
            - '@translator'
            - '@logger'

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    monolog_channels:
        - 'twitter_api'
        - 'status'
        - 'development'
        - 'membership'

    redis_cache:                                                  'App\Cache\RedisCache'

    weaving_the_web_twitter.api_host:                             'api.twitter.com'

    weaving_the_web_twitter.authenticate_application.class:       'App\Twitter\Command\AuthenticateApplicationCommand'
    weaving_the_web_twitter.authentication_uri:                   '/oauth2/token'

    weaving_the_web_twitter.client.class:                         '\Goutte\Client'

    weaving_the_web_twitter.consumer_key:                         '%env(resolve:API_TWITTER_CONSUMER_KEY)%'
    weaving_the_web_twitter.consumer_secret:                      '%env(resolve:API_TWITTER_CONSUMER_SECRET)%'

    weaving_the_web_twitter.http_client.class:                    '\GuzzleHttp\Client'

    weaving_the_web_twitter.oauth_token.default:                  '%env(resolve:API_TWITTER_USER_TOKEN)%'
    weaving_the_web_twitter.oauth_secret.default:                 '%env(resolve:API_TWITTER_USER_SECRET)%'

    weaving_the_web_twitter.entity.archived_status.class:         'App\Api\Entity\ArchivedStatus'
    weaving_the_web_twitter.entity.aggregate.class:               '%weaving_the_web_api.entity.aggregate.class%'
    weaving_the_web_twitter.entity.status.class:                  '%weaving_the_web_api.entity.status.class%'
    weaving_the_web_twitter.entity.token.class:                   '%weaving_the_web_api.entity.token.class%'

    repository.publication_list.class:                            '%weaving_the_web_api.repository.publication_list.class%'

    weaving_the_web_twitter.version:                              '%env(resolve:API_TWITTER_VERSION)%'

    allowed.origin:                                               '%env(resolve:ALLOWED_ORIGIN)%'

    highlight_aggregate_default:                                  '%env(resolve:HIGHLIGHT_AGGREGATE_DEFAULT)%'

    admin_route_name:                                             '%env(resolve:ADMIN_ROUTE_NAME)%'

    redis_host:                                                   '%env(resolve:REDIS_HOST)%'
    redis_port:                                                   '%env(resolve:REDIS_PORT)%'

    valid_audience:                                               '%env(resolve:VALID_AUDIENCE)%'

    authorized_iss:                                               '%env(resolve:AUTHORIZED_ISS)%'
