services:
    _defaults:
        public: true

    # If you need to access services in a test, create an alias
    # and then fetch that alias from the container. As a convention,
    # aliases are prefixed with test. For example:
    #
    # test.App\Service\MyService: '@App\Service\MyService'

    test.event_repository.ownership_batch_collected: '@App\Infrastructure\Curation\Repository\OwnershipBatchCollectedEventRepository'

    test.event_repository.member_profile_collected: '@App\Infrastructure\Curation\Repository\MemberProfileCollectedEventRepository'

    test.App\Infrastructure\Amqp\MessageBus\PublicationMessageDispatcher: '@App\Infrastructure\Amqp\MessageBus\PublicationMessageDispatcher'

    test.App\Domain\Subscription\Console\ListMemberSubscriptionsCommand: '@App\Domain\Subscription\Console\ListMemberSubscriptionsCommand'

    test.App\Domain\Subscription\Console\ListMemberSubscribeesCommand: '@App\Domain\Subscription\Console\ListMemberSubscribeesCommand'

    test.App\Domain\Subscription\Console\UnfollowDiffSubscriptionsSubscribeesCommand: '@App\Domain\Subscription\Console\UnfollowDiffSubscriptionsSubscribeesCommand'

    test.App\Infrastructure\Curation\Repository\FriendsListCollectedEventRepository: '@App\Infrastructure\Curation\Repository\FriendsListCollectedEventRepository'

    test.App\Infrastructure\Curation\Repository\FollowersListCollectedEventRepository: '@App\Infrastructure\Curation\Repository\FollowersListCollectedEventRepository'

    test.App\Domain\Subscription\Console\UnfollowInactiveMembersCommand: '@App\Domain\Subscription\Console\UnfollowInactiveMembersCommand'
