services:
    _defaults:
        public: true

    # If you need to access services in a test, create an alias
    # and then fetch that alias from the container. As a convention,
    # aliases are prefixed with test. For example:
    #
    # test.App\Service\MyService: '@App\Service\MyService'

    test.event_repository.ownership_batch_collected: '@App\Infrastructure\Collection\Repository\OwnershipBatchCollectedEventRepository'

    test.event_repository.member_profile_collected: '@App\Infrastructure\Collection\Repository\MemberProfileCollectedEventRepository'

    test.App\Infrastructure\Amqp\MessageBus\PublicationMessageDispatcher: '@App\Infrastructure\Amqp\MessageBus\PublicationMessageDispatcher'

    test.App\Domain\Subscription\Console\ListMemberSubscriptionsCommand: '@App\Domain\Subscription\Console\ListMemberSubscriptionsCommand'

    test.App\Infrastructure\Collection\Repository\MemberFriendsListCollectedEventRepository: '@App\Infrastructure\Collection\Repository\MemberFriendsListCollectedEventRepository'