services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    test.doctrine.dbal.connection: '@Doctrine\DBAL\Connection'

    test.event_repository.member_profile_collected:
        '@App\Twitter\Infrastructure\Curation\Repository\MemberProfileCollectedEventRepository'

    test.App\Twitter\Infrastructure\Amqp\MessageBus\DispatchAmqpMessagesToFetchTweets: '@App\Twitter\Infrastructure\Amqp\MessageBus\DispatchAmqpMessagesToFetchTweets'

    test.App\Twitter\Infrastructure\Subscription\Console\ListMemberSubscriptionsCommand: '@App\Twitter\Infrastructure\Subscription\Console\ListMemberSubscriptionsCommand'
    test.App\Twitter\Infrastructure\Subscription\Console\ListMemberSubscribeesCommand: '@App\Twitter\Infrastructure\Subscription\Console\ListMemberSubscribeesCommand'
    test.App\Twitter\Infrastructure\Subscription\Console\UnfollowDiffSubscriptionsSubscribeesCommand: '@App\Twitter\Infrastructure\Subscription\Console\UnfollowDiffSubscriptionsSubscribeesCommand'
    test.App\Twitter\Infrastructure\Subscription\Console\UnfollowInactiveMembersCommand: '@App\Twitter\Infrastructure\Subscription\Console\UnfollowInactiveMembersCommand'
    test.App\Twitter\Infrastructure\Http\Security\Authorization\Console\AuthorizeApplicationCommand: '@App\Twitter\Infrastructure\Http\Security\Authorization\Console\AuthorizeApplicationCommand'

    App\Twitter\Domain\Http\Client\MemberProfileAwareHttpClientInterface:
        factory: [ 'App\Tests\Twitter\Infrastructure\Http\Builder\Client\MemberProfileAwareHttpClientBuilder', 'build' ]

    test.App\Membership\Domain\Repository\MemberRepositoryInterface: '@App\Membership\Domain\Repository\MemberRepositoryInterface'
    test.App\Twitter\Domain\Http\AccessToken\Repository\TokenRepositoryInterface: '@App\Twitter\Domain\Http\AccessToken\Repository\TokenRepositoryInterface'
    test.App\Twitter\Infrastructure\Curation\Repository\ListsBatchCollectedEventRepository: '@App\Twitter\Domain\Curation\Repository\ListsBatchCollectedEventRepositoryInterface'
    test.App\Twitter\Infrastructure\Curation\Repository\FriendsListCollectedEventRepository: '@App\Twitter\Infrastructure\Curation\Repository\FriendsListCollectedEventRepository'
    test.App\Twitter\Infrastructure\Curation\Repository\FollowersListCollectedEventRepository: '@App\Twitter\Infrastructure\Curation\Repository\FollowersListCollectedEventRepository'

    App\Twitter\Infrastructure\Http\Security\Authorization\AuthorizeAccess:
        factory: ['App\Tests\Twitter\Infrastructure\Http\Security\Authorization\Builder\AuthorizeAccessBuilder', 'build']

    App\Twitter\Domain\Http\Client\HttpClientInterface:
        factory: ['App\Tests\Twitter\Infrastructure\Http\Builder\Client\HttpClientBuilder', 'willAllowPublishersListToBeImportedForMemberHavingScreenName']
        arguments:
            - '@App\Membership\Domain\Repository\MemberRepositoryInterface'
            - '@logger'
            - !php/const 'App\Tests\Twitter\Infrastructure\PublishersList\Console\ImportMemberPublishersListsCommandTest::SCREEN_NAME'

    App\Twitter\Domain\Http\Client\ListAwareHttpClientInterface:
        factory: ['App\Tests\Twitter\Infrastructure\Http\Builder\Client\ListAwareHttpClientBuilder', 'willAllowPublishersListToBeImportedForMemberHavingScreenName']

    App\Twitter\Domain\Http\Client\TweetAwareHttpClientInterface:
        factory: ['App\Tests\Twitter\Infrastructure\Http\Builder\Client\TweetAwareHttpClientBuilder', 'willEnsureMemberHavingNameExists']
        arguments:
            - '@App\Membership\Domain\Repository\MemberRepositoryInterface'

    App\Twitter\Domain\Http\Client\MembersBatchAwareHttpClientInterface:
        factory: ['App\Tests\Twitter\Infrastructure\Http\Builder\Client\MembersBatchAwareHttpClientBuilder', 'willAddMembersToList']

    App\Membership\Domain\Repository\NetworkRepositoryInterface:
        factory: ['App\Tests\Membership\Builder\Repository\NetworkRepositoryBuilder', 'build']
        arguments:
            - '@App\Membership\Domain\Repository\MemberRepositoryInterface'
            - '@logger'

    test.App\Membership\Infrastructure\Console\AddMembersBatchToListCommand:
        '@App\Membership\Infrastructure\Console\AddMembersBatchToListCommand'

    test.App\Twitter\Infrastructure\PublishersList\Console\ImportMemberPublishersListsCommand:
        '@App\Twitter\Infrastructure\PublishersList\Console\ImportMemberPublishersListsCommand'

    test.App\Twitter\Infrastructure\Subscription\Console\ListSubscriptionsToPublishersListsCommand:
        '@App\Twitter\Infrastructure\Subscription\Console\ListSubscriptionsToPublishersListsCommand'

    test.App\Twitter\Domain\Curation\Repository\ListsBatchCollectedEventRepositoryInterface:
        '@App\Twitter\Domain\Curation\Repository\ListsBatchCollectedEventRepositoryInterface'
