parameters:
    command.map_aggregate_status_collection.class:                              'App\StatusCollection\Mapping\Command\MapAggregateStatusCollectionCommand'
    command.map_status_collection.class:                                        'App\StatusCollection\Mapping\Command\MapStatusCollectionCommand'
    command.select_status_collection.class:                                     'App\StatusCollection\Command\SelectStatusCollectionCommand'
    weaving_the_web_amqp.consumer.conversation_status.class:                    'App\Conversation\Consumer\ConversationStatusConsumer'
    weaving_the_web_amqp.consumer.timely_status.class:                          'App\Aggregate\Consumer\TimelyStatusConsumer'
    weaving_the_web_amqp.producer.produce_conversation_messages_command.class:  'App\Conversation\Producer\ProduceConversationMessagesCommand'
    weaving_the_web_amqp.producer.produce_timely_status_messages_command.class: 'App\Aggregate\Producer\ProduceTimelyStatusMessagesCommand'
    weaving_the_web_amqp.producer.produce_member_messages_command.class:        'App\Conversation\Producer\ProduceMemberMessagesCommand'
    weaving_the_web_amqp.produce_lists_members_command.class:                   'WeavingTheWeb\Bundle\AmqpBundle\Command\ProduceListsMembersCommand'
    weaving_the_web_amqp.twitter.user_status.class:                             'WeavingTheWeb\Bundle\AmqpBundle\Twitter\UserStatus'

services:
    command.select_status_collection:
        class:                       "%command.select_status_collection.class%"
        properties:
            statusRepository:       "@weaving_the_web_twitter.repository.status"
        tags:
            - { name: 'console.command' }

    command.map_status_collection:
        class:                      "%command.map_status_collection.class%"
        properties:
            statusRepository:       "@weaving_the_web_twitter.repository.status"
            refreshStatusMapping:   "@mapping.refresh_status"
            oauthToken:             "%weaving_the_web_twitter.oauth_token.default%"
            oauthSecret:            "%weaving_the_web_twitter.oauth_secret.default%"
        tags:
            - { name: 'console.command' }

    command.map_aggregate_status_collection:
        class:                      "%command.map_aggregate_status_collection.class%"
        properties:
            logger:                             "@monolog.logger.status"
            statusRepository:                   "@weaving_the_web_twitter.repository.status"
            refreshStatusMapping:               "@mapping.refresh_status"
            oauthToken:                         "%weaving_the_web_twitter.oauth_token.default%"
            oauthSecret:                        "%weaving_the_web_twitter.oauth_secret.default%"
            timeAfterWhichOperationIsSkipped:   '%operations_skipped_after%'
            timeBeforeWhichOperationIsSkipped:  '%operations_skipped_before%'
        tags:
            - { name: 'console.command' }

    weaving_the_web_amqp.consumer.conversation_status:
        class:                        "%weaving_the_web_amqp.consumer.conversation_status.class%"
        calls:
            - [ 'setLogger',            [ '@monolog.logger.status'] ]
            - [ 'setUserRepository',    [ '@user_manager'] ]
        properties:
            aggregateRepository:    "@weaving_the_web_twitter.repository.aggregate"
            entityManager:          "@doctrine.orm.entity_manager"
            operationClock:         "@operation.clock"
            statusAccessor:         "@weaving_the_web.accessor.status"
            statusRepository:       "@weaving_the_web_twitter.repository.status"

    weaving_the_web_amqp.consumer.timely_status:
        class:                        "%weaving_the_web_amqp.consumer.timely_status.class%"
        calls:
            - [ 'setLogger',            [ '@monolog.logger.status'] ]
            - [ 'setUserRepository',    [ '@user_manager'] ]
        properties:
            aggregateRepository:    "@weaving_the_web_twitter.repository.aggregate"
            entityManager:          "@doctrine.orm.entity_manager"
            operationClock:         "@operation.clock"
            statusAccessor:         "@weaving_the_web.accessor.status"
            timelyStatusRepository:   "@repository.timely_status"

    weaving_the_web_amqp.twitter:
        class:                       "%weaving_the_web_amqp.twitter.user_status.class%"
        properties:
            operationClock:          "@operation.clock"
        calls:
            - [ 'setLogger',            [ '@monolog.logger.status'] ]

    weaving_the_web_amqp.twitter.lists_member_status:
        class:                       "%weaving_the_web_amqp.produce_lists_members_command.class%"
        properties:
            operationClock:          "@operation.clock"
        tags:
            - { name: 'console.command' }

    weaving_the_web_amqp.twitter.user_status:
        class:                        "%weaving_the_web_amqp.twitter.user_status.class%"
        calls:
            - [ 'setSerializer',        [ '@weaving_the_web_twitter.serializer.user_status'] ]
            - [ 'setLogger',            [ '@monolog.logger.status'] ]
            - [ 'setUserRepository',    [ '@user_manager'] ]
        properties:
            operationClock:             "@operation.clock"

    weaving_the_web_amqp.producer.conversation_status:
        class:               "%weaving_the_web_amqp.producer.produce_conversation_messages_command.class%"
        properties:
            operationClock:  "@operation.clock"
            filesystem:      "@filesystem"
            statusDirectory: "%kernel.root_dir%/../src/App/Resources/statuses"
        tags:
            - { name: 'console.command' }

    weaving_the_web_amqp.producer.timely_status:
        class:               "%weaving_the_web_amqp.producer.produce_timely_status_messages_command.class%"
        properties:
            operationClock:  "@operation.clock"
            statusDirectory: "%kernel.root_dir%/../src/App/Resources/statuses"
        tags:
            - { name: 'console.command' }

    weaving_the_web_amqp.producer.member_status:
        class:               "%weaving_the_web_amqp.producer.produce_member_messages_command.class%"
        properties:
            operationClock:  "@operation.clock"
            statusDirectory: "%kernel.root_dir%/../src/App/Resources/statuses"
        tags:
            - { name: 'console.command' }
