services:
    controller.authentication:
        class: 'App\Member\Authentication\Controller\AuthenticationController'
        properties:
            authenticator:        '@app.authenticator'

    controller.list:
        class: 'App\Aggregate\Controller\ListController'
        properties:
            aggregateRepository:    '@repository.aggregate'
            allowedOrigin:          '%allowed.origin%'
            environment:            '%kernel.environment%'
            logger:                 '@logger'
            memberRepository:       '@user_manager'
            timelyStatusRepository: '@repository.timely_status'
