services:
    controller.authentication:
        class: 'App\Member\Authentication\Controller\AuthenticationController'
        properties:
            authenticator:        '@app.authenticator'

    controller.list:
        class: 'App\Aggregate\Controller\ListController'
        properties:
            allowedOrigin:              '%allowed.origin%'
            aggregateLikesProducer:     '@old_sound_rabbit_mq.weaving_the_web_amqp.producer.aggregates_likes_producer'
            aggregateRepository:        '@repository.aggregate'
            aggregateStatusesProducer:  '@old_sound_rabbit_mq.weaving_the_web_amqp.twitter.aggregates_status_producer'
            environment:                '%kernel.environment%'
            highlightRepository:        '@repository.highlight'
            logger:                     '@logger'
            memberRepository:           '@user_manager'
            timelyStatusRepository:     '@repository.timely_status'
            tokenRepository:            '@weaving_the_web_api.repository.token'

    controller.logged_in_member:
        class: 'App\Member\Controller\LoggedInMemberController'
        properties:
            logger:                        '@logger'
            authenticationTokenRepository: '@repository.authentication_token'
            allowedOrigin:                 '%allowed.origin%'
            environment:                   '%kernel.environment%'
