parameters:

    weaving_the_web_api.entity.token.class:         'WeavingTheWeb\Bundle\ApiBundle\Entity\Token'
    weaving_the_web_api.entity.whisperer.class:     'WeavingTheWeb\Bundle\ApiBundle\Entity\Whisperer'

services:

    repository.not_found_status:
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        class: 'App\Status\Entity\NotFoundStatus'
        arguments:
            - 'App\Status\Entity\NotFoundStatus'

    weaving_the_web_api.repository.token:
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        class: '%weaving_the_web_api.repository.token.class%'
        arguments:
            - '%weaving_the_web_api.entity.token.class%'

    weaving_the_web_api.repository.whisperer:
        factory: ['@doctrine.orm.entity_manager', 'getRepository' ]
        class: '%weaving_the_web_api.repository.whisperer.class%'
        arguments:
            - '%weaving_the_web_api.entity.whisperer.class%'
