version: '3.8'

services:

    amqp:
        build:
            context: .
            dockerfile: './amqp/Dockerfile'
        expose:
            - "5672"
        restart: always
        env_file:
            - '../../.env.local'
        volumes:
            - '../volumes/amqp:/var/lib/rabbitmq'

    app:
        build:
            context: .
            dockerfile: './worker/Dockerfile'
        env_file:
            - '../../.env.local'
        restart: always
        volumes:
            - '../containers/service/templates/extensions.ini.dist:/usr/local/etc/php/conf.d/extensions.ini'
            - '../containers/service/templates:/templates'
            - '../../:/var/www/revue-de-presse.org'
            - '../../../shared:/var/www/shared'

    cache:
        image: redis:7-bullseye
        command: redis-server --appendonly yes
        restart: always
        volumes:
            - '../volumes/cache:/data'

    database:
        build: ./database
        restart: always
        ports:
            - "127.0.0.1:3306:3306"
        env_file:
            - '../../.env.local'
        volumes:
            - '../volumes/database:/var/lib/mysql'
            - './database/templates/database.cnf:/etc/mysql/mariadb.conf.d/docker.cnf'

    service:
        build:
            context: .
            dockerfile: './service/Dockerfile'
        depends_on:
            - cache
        env_file:
            - '../../.env.local'
        restart: always
        volumes:
            - './service/templates/extensions.ini.dist:/usr/local/etc/php/conf.d/extensions.ini'
            - './service/templates/docker.conf:/usr/local/etc/php-fpm.d/docker.conf'
            - './service/templates/empty.conf:/usr/local/etc/php-fpm.d/zz-docker.conf'
            - './service/templates/www.conf:/usr/local/etc/php-fpm.d/www.conf'
            - '../../:/var/www/revue-de-presse.org'
            - '../../../shared:/var/www/shared'

    worker:
        build:
            context: .
            dockerfile: './worker/Dockerfile'
        depends_on:
            - amqp
        env_file:
            - '../../.env.local'
        volumes:
            - '../../:/var/www/revue-de-presse.org'
            - '../../../shared:/var/www/shared'
