version: '3.8'

name: 'wildcard'

x-shared: &shared
  build:
    context: .
    dockerfile: './worker/Dockerfile'
  env_file:
    - '../../.env.local'
  volumes:
    - './_scripts/:/scripts'
    - './worker/templates:/templates'
    - './worker/templates/extensions.ini.dist:/usr/local/etc/php/conf.d/extensions.ini'
    - '../../../shared:/var/www/shared'
  depends_on:
    - 'amqp'

services:

  amqp:
    build: './amqp'
    expose:
      - "5672"
    restart: 'always'
    env_file:
      - '../../.env.local'

  app:
    <<: *shared

  database:
    image: 'postgres:14-bullseye'
    restart: 'always'
    env_file:
      - '../../.env.local'

  process-manager:
    build:
      context: .
      dockerfile: './process-manager/Dockerfile'
    env_file:
      - '../../.env.local'
    restart: 'always'
    volumes:
      - './_scripts/:/scripts'
      - './worker/templates:/templates'
      - '../../../shared:/var/www/shared'

  worker:
    <<: *shared
