version: '3.8'

name: 'revue-de-presse.org'

x-vol: &shared-volumes
  volumes:
    - './_scripts/:/scripts'
    - './worker/templates:/templates'
    - './worker/templates/extensions.ini.dist:/usr/local/etc/php/conf.d/extensions.ini'
    - '../../../shared:/var/www/shared'

x-shared: &shared
  env_file:
    - '../../.env.local'
  restart: 'always'
  <<: *shared-volumes

x-worker: &worker
  build:
    context: .
    dockerfile: './worker/Dockerfile'
  <<: *shared

services:

  amqp:
    build: './amqp'
    expose:
      - "5672"
    restart: 'always'
    env_file:
      - '../../.env.local'

  app:
    <<: *worker

  database:
    image: 'postgres:14-bullseye'
    restart: 'always'
    env_file:
      - '../../.env.local'

  process-manager:
    build:
      context: .
      dockerfile: './process-manager/Dockerfile'
    depends_on:
      - 'worker'
    <<: *shared

  worker:
    <<: *worker

