name: wildcard

services:

    amqp:
        build: './amqp'
        expose:
            - "5672"
        restart: 'always'
        env_file:
            - '../../.env.local'

    database:
        image: 'postgres:14-bullseye'
        restart: 'always'
        env_file:
            - '../../.env.local'

    worker:
        build:
            context: .
            dockerfile: './worker/Dockerfile'
        volumes:
            - './_scripts/:/scripts'
            - './service/templates/extensions.ini.dist:/usr/local/etc/php/conf.d/extensions.ini'
            - '../../:/var/www/worker'
            - '../../../shared:/var/www/shared'
        depends_on:
            - 'amqp'

version: '3.8'
