version: '3.8'

name: 'revue-de-presse-org'

services:

    app:
        build:
            context: .
            dockerfile: './app/Dockerfile'
        env_file:
            - '../../.env.local'
        restart: always
        volumes:
            - './service/templates/extensions.ini.dist:/usr/local/etc/php/conf.d/extensions.ini'
            - './service/templates/:/templates/'
            - '../../:/var/www/api.revue-de-presse.org/'
            - '../../../shared/:/var/www/shared/'
            - '../../../shared/emoji-data/:/var/www/api.revue-de-presse.org/public/emoji-data/'

    cache:
        image: redis:7-bullseye
        command: redis-server --appendonly yes
        restart: always
        volumes:
            - '../volumes/cache:/data'

    service:
        build:
            context: .
            dockerfile: './service/Dockerfile'
        depends_on:
            - cache
        env_file:
            - '../../.env.local'
        restart: always
        volumes:
            - './service/templates/extensions.ini.dist:/usr/local/etc/php/conf.d/extensions.ini'
            - './service/templates/docker.conf:/usr/local/etc/php-fpm.d/docker.conf'
            - './service/templates/empty.conf:/usr/local/etc/php-fpm.d/zz-docker.conf'
            - './service/templates/www.conf:/usr/local/etc/php-fpm.d/www.conf'
            - '../../:/var/www/api.revue-de-presse.org/'
            - '../../../shared/:/var/www/shared/'
            - '../../../shared/emoji-data/:/var/www/api.revue-de-presse.org/public/emoji-data/'
