version: '3.8'

services:

    amqp:
        build:
            context: .
            dockerfile: ./amqp/Dockerfile
        expose:
            - "5672"
        restart: always
        env_file:
            - ../../.env.local
        volumes:
            - ../volumes/amqp:/var/lib/rabbitmq

    app:
        build:
            context: .
            dockerfile: ./service/Dockerfile
        command: tail -f /dev/null
        env_file:
            - ../../.env.local
        restart: always
        volumes:
            - '../containers/service/templates/extensions.ini.dist:/usr/local/etc/php/conf.d/extensions.ini'
            - '../containers/service/templates:/templates'
            - '../volumes/app:/root/.composer'
            - '../../:/var/www/revue-de-presse.org'
            - '../../../shared:/var/www/shared'
        working_dir: '/var/www/revue-de-presse.org'

    cache:
        image: redis
        command: redis-server --appendonly yes
        expose:
            - "6379"
        restart: always
        volumes:
            - ../volumes/cache:/data

    db_read:
        build: ./mysql
        restart: always
        env_file:
            - ../../.env.local
        ports:
            - "127.0.0.1:33062:3306"
        volumes:
            - ../volumes/db_read:/var/lib/mysql

    db_write:
        build: ./mariadb
        restart: always
        ports:
            - "127.0.0.1:33061:3306"
        env_file:
            - ../../.env.local
        volumes:
            - ../volumes/db_write:/var/lib/mysql
            - ./db_write/templates/docker.cnf:/etc/mysql/mariadb.conf.d/docker.cnf

    service:
        build:
            context: .
            dockerfile: ./service/Dockerfile
        restart: always
        volumes:
            - './service/templates/extensions.ini.dist:/usr/local/etc/php/conf.d/extensions.ini'
            - './service/templates/docker.conf:/usr/local/etc/php-fpm.d/docker.conf'
            - './service/templates/empty.conf:/usr/local/etc/php-fpm.d/zz-docker.conf'
            - './service/templates/www.conf:/usr/local/etc/php-fpm.d/www.conf'
            - '../../:/var/www/revue-de-presse.org'
        env_file:
            - ../../.env.local
        depends_on:
            - cache
        working_dir: '/var/www/revue-de-presse.org'

    worker:
        build:
            context: .
            dockerfile: ./worker/Dockerfile
        volumes:
            - ../../:/var/www/revue-de-presse.org
        depends_on:
            - amqp
