version: '3.8'

services:

    app:
        build:
            context: .
            dockerfile: './app/Dockerfile'
        env_file:
            - '../../.env.local'
        restart: always
        volumes:
            - './service/templates/extensions.ini.dist:/usr/local/etc/php/conf.d/extensions.ini'
            - './service/templates/:/templates/'
            - '../../../shared/:/var/www/shared/'

    cache:
        image: redis:7-bullseye
        command: redis-server --appendonly yes
        restart: always
        volumes:
            - '../volumes/cache:/data'

    service:
        build:
            context: .
            dockerfile: './service/Dockerfile'
        depends_on:
            - cache
        env_file:
            - '../../.env.local'
        restart: always
        volumes:
            - './service/templates/extensions.ini.dist:/usr/local/etc/php/conf.d/extensions.ini'
            - './service/templates/docker.conf:/usr/local/etc/php-fpm.d/docker.conf'
            - './service/templates/empty.conf:/usr/local/etc/php-fpm.d/zz-docker.conf'
            - '../../../shared/:/var/www/shared/'
            - type: bind
              source: './service/templates/www.conf'
              target: '/usr/local/etc/php-fpm.d/www.conf'
              bind:
                  create_host_path: false
