weaving_the_web_twitter:
    prefix:   '/api/twitter'
    resource: "@WeavingTheWebTwitterBundle/Controller/"
    type:     annotation

authentication_verify:
    path:     '/api/authentication/verify'
    defaults: { _controller: controller.authentication:verify }

aggregate:
    path:     '/api/twitter/admin/lists'
    defaults: { _controller: controller.list:getAggregates }

member:
    path:     '/api/twitter/admin/members'
    defaults: { _controller: controller.list:getMembers }

status:
    path:     '/api/twitter/admin/statuses'
    defaults: { _controller: controller.list:getStatuses }

collect:
    path:     '/api/twitter/admin/collect'
    defaults: { _controller: controller.list:requestCollection }
    methods:  [POST, OPTIONS]

unlock:
    path:     '/api/twitter/admin/unlock-aggregate'
    defaults: { _controller: controller.list:unlockAggregate }
    methods:  [POST, OPTIONS]
