name: Revue-de-presse.org

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-20.04

    services:
      mysql:
        image: mariadb:10.8
        env:
          MARIADB_DATABASE: test
          MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
        ports:
          - 3306:3306

      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Install packages
        run: sudo apt-get install bash gzip tar wget

      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2.2

      - name: Cache composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Add HTTP basic auth credentials
        run: echo '${{ secrets.COMPOSER_AUTH_JSON }}' > $GITHUB_WORKSPACE/auth.json

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Remove auth.json file
        run: rm -f $GITHUB_WORKSPACE/auth.json

      - name: Copy test environment variables configuration file
        run: |
          cat ${GITHUB_WORKSPACE}/provisioning/continuous-integration/parameters_test.yml.dist \
          | sed -E 's#_APP_SECRET_#'"${APP_SECRET}"'#g' \
          | sed -E 's#_PASS_#'"${MARIADB_ROOT_PASSWORD}"'#g' \
          > ${GITHUB_WORKSPACE}/.env.test

      - name: Create test database schema
        run: php bin/console doctrine:schema:create -n -e test

      - name: Run unit tests
        run: make test
